-- =====================================================================
-- Requêtes de Diagnostic - Traitement AR 46850719
-- =====================================================================
-- Date de création : 22/01/2026
-- Auteur : GitHub Copilot
-- Contexte : Analyse du traitement AR terminé en avertissement
-- 
-- INCIDENT : Traitement 46850719 en warning
-- - Corrections de lieux effectuées
-- - Erreur "Aucun règlement n'a été créé par le traitement 46850843"
-- =====================================================================

-- =====================================================================
-- 1. DÉTAILS DES CONCURRENT REQUESTS
-- =====================================================================
SELECT FCR.REQUEST_ID, 
       FCP.USER_CONCURRENT_PROGRAM_NAME AS PROGRAMME,
       DECODE(FCR.PHASE_CODE, 'C', 'Completed', 'R', 'Running', 'P', 'Pending', FCR.PHASE_CODE) AS PHASE,
       DECODE(FCR.STATUS_CODE, 'C', 'Normal', 'E', 'Error', 'G', 'Warning', 'W', 'Paused', FCR.STATUS_CODE) AS STATUT,
       TO_CHAR(FCR.ACTUAL_START_DATE, 'DD/MM/YYYY HH24:MI:SS') AS DEBUT,
       TO_CHAR(FCR.ACTUAL_COMPLETION_DATE, 'DD/MM/YYYY HH24:MI:SS') AS FIN,
       ROUND((FCR.ACTUAL_COMPLETION_DATE - FCR.ACTUAL_START_DATE) * 24 * 60, 2) AS DUREE_MIN,
       FCR.ARGUMENT_TEXT AS ARGUMENTS,
       FCR.COMPLETION_TEXT AS MESSAGE_FIN
FROM APPLSYS.FND_CONCURRENT_REQUESTS FCR
JOIN APPLSYS.FND_CONCURRENT_PROGRAMS_VL FCP 
    ON FCR.CONCURRENT_PROGRAM_ID = FCP.CONCURRENT_PROGRAM_ID
WHERE FCR.REQUEST_ID IN (46850719, 46850843, 46850851, 46850854)
ORDER BY FCR.REQUEST_ID;

-- =====================================================================
-- 2. CASH RECEIPTS CONCERNÉS
-- =====================================================================
SELECT CR.CASH_RECEIPT_ID,
       CR.RECEIPT_NUMBER AS NUMERO_REGLEMENT,
       CR.AMOUNT AS MONTANT,
       CR.CURRENCY_CODE AS DEVISE,
       CR.STATUS AS STATUT,
       TO_CHAR(CR.RECEIPT_DATE, 'DD/MM/YYYY') AS DATE_REGLEMENT,
       TO_CHAR(CR.CREATION_DATE, 'DD/MM/YYYY HH24:MI') AS DATE_CREATION,
       FU.USER_NAME AS CREATEUR,
       HCA.ACCOUNT_NUMBER AS COMPTE_CLIENT,
       HP.PARTY_NAME AS NOM_CLIENT
FROM AR.AR_CASH_RECEIPTS_ALL CR
LEFT JOIN AR.HZ_CUST_ACCOUNTS HCA ON CR.PAY_FROM_CUSTOMER = HCA.CUST_ACCOUNT_ID
LEFT JOIN AR.HZ_PARTIES HP ON HCA.PARTY_ID = HP.PARTY_ID
LEFT JOIN APPLSYS.FND_USER FU ON CR.CREATED_BY = FU.USER_ID
WHERE CR.CASH_RECEIPT_ID IN (4965487, 4966496);

-- =====================================================================
-- 3. LOTS AR (BATCHES)
-- =====================================================================
SELECT B.BATCH_ID,
       B.NAME AS NOM_LOT,
       BS.NAME AS SOURCE_LOT,
       DECODE(B.STATUS, 'CL', 'Closed', 'OP', 'Open', B.STATUS) AS STATUT,
       TO_CHAR(B.GL_DATE, 'DD/MM/YYYY') AS DATE_GL,
       B.CONTROL_COUNT AS NB_ATTENDU,
       B.CONTROL_AMOUNT AS MONTANT_ATTENDU,
       (SELECT COUNT(*) FROM AR.AR_CASH_RECEIPTS_ALL CR WHERE CR.BATCH_ID = B.BATCH_ID) AS NB_REGLEMENTS,
       TO_CHAR(B.CREATION_DATE, 'DD/MM/YYYY HH24:MI') AS DATE_CREATION
FROM AR.AR_BATCHES_ALL B
LEFT JOIN AR.AR_BATCH_SOURCES_ALL BS ON B.BATCH_SOURCE_ID = BS.BATCH_SOURCE_ID
WHERE B.BATCH_ID IN (3515294, 3515299)
ORDER BY B.BATCH_ID;

-- =====================================================================
-- 4. SITES CLIENTS (AVANT/APRÈS CORRECTION)
-- =====================================================================
SELECT HSU.SITE_USE_ID,
       HCA.ACCOUNT_NUMBER AS COMPTE_CLIENT,
       HP.PARTY_NAME AS NOM_CLIENT,
       HL.ADDRESS1 || ', ' || HL.CITY AS ADRESSE,
       HSU.LOCATION AS CODE_LIEU,
       HSU.SITE_USE_CODE AS TYPE_SITE,
       HSU.STATUS AS STATUT,
       HSU.PRIMARY_FLAG AS PRINCIPAL,
       CASE 
           WHEN HSU.SITE_USE_ID IN (470956, 9971794) THEN 'ANCIEN (remplacé)'
           WHEN HSU.SITE_USE_ID IN (483547, 9971825) THEN 'NOUVEAU (actif)'
       END AS ROLE_CORRECTION
FROM AR.HZ_CUST_SITE_USES_ALL HSU
JOIN AR.HZ_CUST_ACCT_SITES_ALL HCAS ON HSU.CUST_ACCT_SITE_ID = HCAS.CUST_ACCT_SITE_ID
JOIN AR.HZ_CUST_ACCOUNTS HCA ON HCAS.CUST_ACCOUNT_ID = HCA.CUST_ACCOUNT_ID
JOIN AR.HZ_PARTIES HP ON HCA.PARTY_ID = HP.PARTY_ID
JOIN AR.HZ_PARTY_SITES HPS ON HCAS.PARTY_SITE_ID = HPS.PARTY_SITE_ID
JOIN AR.HZ_LOCATIONS HL ON HPS.LOCATION_ID = HL.LOCATION_ID
WHERE HSU.SITE_USE_ID IN (470956, 483547, 9971794, 9971825)
ORDER BY HP.PARTY_NAME, HSU.SITE_USE_ID;

-- =====================================================================
-- 5. HIÉRARCHIE DES TRAITEMENTS (PARENT/ENFANTS)
-- =====================================================================
SELECT FCR.REQUEST_ID,
       FCR.PARENT_REQUEST_ID,
       FCP.USER_CONCURRENT_PROGRAM_NAME AS PROGRAMME,
       DECODE(FCR.STATUS_CODE, 'C', 'Normal', 'E', 'Error', 'G', 'Warning', FCR.STATUS_CODE) AS STATUT,
       FCR.COMPLETION_TEXT AS MESSAGE
FROM APPLSYS.FND_CONCURRENT_REQUESTS FCR
JOIN APPLSYS.FND_CONCURRENT_PROGRAMS_VL FCP 
    ON FCR.CONCURRENT_PROGRAM_ID = FCP.CONCURRENT_PROGRAM_ID
WHERE FCR.PARENT_REQUEST_ID = 46850719
   OR FCR.REQUEST_ID = 46850719
ORDER BY FCR.REQUEST_ID;

-- =====================================================================
-- 6. TRAITEMENT 46850843 - DÉTAIL COMPLET
-- =====================================================================
SELECT FCR.REQUEST_ID,
       FCP.USER_CONCURRENT_PROGRAM_NAME AS PROGRAMME,
       FCP.CONCURRENT_PROGRAM_NAME AS NOM_TECHNIQUE,
       FCR.PHASE_CODE,
       FCR.STATUS_CODE,
       TO_CHAR(FCR.REQUEST_DATE, 'DD/MM/YYYY HH24:MI:SS') AS DATE_DEMANDE,
       TO_CHAR(FCR.ACTUAL_START_DATE, 'DD/MM/YYYY HH24:MI:SS') AS DEBUT,
       TO_CHAR(FCR.ACTUAL_COMPLETION_DATE, 'DD/MM/YYYY HH24:MI:SS') AS FIN,
       FCR.ARGUMENT_TEXT,
       FCR.COMPLETION_TEXT,
       FU.USER_NAME AS DEMANDEUR
FROM APPLSYS.FND_CONCURRENT_REQUESTS FCR
JOIN APPLSYS.FND_CONCURRENT_PROGRAMS_VL FCP 
    ON FCR.CONCURRENT_PROGRAM_ID = FCP.CONCURRENT_PROGRAM_ID
LEFT JOIN APPLSYS.FND_USER FU ON FCR.REQUESTED_BY = FU.USER_ID
WHERE FCR.REQUEST_ID = 46850843;

-- =====================================================================
-- 7. VÉRIFIER SI D'AUTRES RECEIPTS ONT ÉTÉ CRÉÉS LE MÊME JOUR
-- =====================================================================
SELECT COUNT(*) AS NB_RECEIPTS,
       CR.STATUS,
       TO_CHAR(CR.CREATION_DATE, 'DD/MM/YYYY') AS DATE_CREATION
FROM AR.AR_CASH_RECEIPTS_ALL CR
WHERE TRUNC(CR.CREATION_DATE) = TRUNC(SYSDATE - 1) -- 21/01/2026
GROUP BY CR.STATUS, TO_CHAR(CR.CREATION_DATE, 'DD/MM/YYYY')
ORDER BY NB_RECEIPTS DESC;
