-- =====================================================================
-- Monitoring des Jobs Talend - Tables FLOW_LOGS (Schéma DKA)
-- =====================================================================
-- Date de création : 30/12/2024
-- Auteur : GitHub Copilot
-- Base de données : Oracle EBS 19.25.0.0.0
--
-- DESCRIPTION : Requêtes de monitoring et diagnostic pour les jobs
--               Talend stockés dans les tables DKA_SCTLFLUX_* et
--               DKA_IAPCTRFLUX_*
--
-- VOIR : FLOW_LOGS_Talend_Documentation.md
-- =====================================================================

-- =====================================================================
-- 1. FLUX EAI/HERCULE - Synthèse des exports comptables
-- =====================================================================

-- Vue d'ensemble des dernières exécutions
SELECT 
    TRUNC(DATE_DEBUT) AS DATE_EXECUTION,
    COUNT(*) AS NB_EXECUTIONS,
    SUM(NB_PIECE) AS TOTAL_PIECES,
    ROUND(SUM(DEBIT), 2) AS TOTAL_DEBIT,
    ROUND(SUM(CREDIT), 2) AS TOTAL_CREDIT,
    ROUND(SUM(DEBIT) - SUM(CREDIT), 2) AS ECART,
    SUM(CASE WHEN TRAITE = 1 THEN 1 ELSE 0 END) AS NB_TRAITES,
    SUM(CASE WHEN TRAITE = 0 THEN 1 ELSE 0 END) AS NB_EN_ATTENTE
FROM DKA.DKA_SCTLFLUX_EAI
WHERE DATE_DEBUT >= TRUNC(SYSDATE) - 7
GROUP BY TRUNC(DATE_DEBUT)
ORDER BY DATE_EXECUTION DESC;

-- Détail des exécutions avec durée
SELECT 
    CODE_FOLIO,
    TO_CHAR(DATE_DEBUT, 'DD/MM/YYYY HH24:MI:SS') AS DEBUT,
    TO_CHAR(DATE_FIN, 'DD/MM/YYYY HH24:MI:SS') AS FIN,
    ROUND((DATE_FIN - DATE_DEBUT) * 24 * 60, 2) AS DUREE_MINUTES,
    NB_PIECE,
    ROUND(DEBIT, 2) AS DEBIT,
    ROUND(CREDIT, 2) AS CREDIT,
    ROUND(DEBIT - CREDIT, 2) AS ECART,
    CASE WHEN TRAITE = 1 THEN 'Traité' ELSE 'En attente' END AS STATUT,
    FICHIER
FROM DKA.DKA_SCTLFLUX_EAI
WHERE DATE_DEBUT >= TRUNC(SYSDATE) - 7
ORDER BY DATE_DEBUT DESC;

-- Identifier les exports non équilibrés (DEBIT != CREDIT)
SELECT 
    CODE_FOLIO,
    TO_CHAR(DATE_DEBUT, 'DD/MM/YYYY HH24:MI:SS') AS DATE_EXEC,
    NB_PIECE,
    ROUND(DEBIT, 2) AS DEBIT,
    ROUND(CREDIT, 2) AS CREDIT,
    ROUND(DEBIT - CREDIT, 2) AS ECART,
    FICHIER
FROM DKA.DKA_SCTLFLUX_EAI
WHERE ABS(DEBIT - CREDIT) > 0.01  -- Tolérance 1 centime
AND DATE_DEBUT >= TRUNC(SYSDATE) - 30
ORDER BY ABS(DEBIT - CREDIT) DESC;

-- Analyse performance : durée moyenne par volume
SELECT 
    TRUNC(DATE_DEBUT) AS DATE_EXEC,
    COUNT(*) AS NB_JOBS,
    ROUND(AVG(NB_PIECE), 0) AS MOY_PIECES,
    ROUND(AVG((DATE_FIN - DATE_DEBUT) * 24 * 60), 2) AS DUREE_MOY_MIN,
    ROUND(MAX((DATE_FIN - DATE_DEBUT) * 24 * 60), 2) AS DUREE_MAX_MIN,
    ROUND(MIN((DATE_FIN - DATE_DEBUT) * 24 * 60), 2) AS DUREE_MIN_MIN
FROM DKA.DKA_SCTLFLUX_EAI
WHERE DATE_DEBUT >= TRUNC(SYSDATE) - 30
AND DATE_FIN IS NOT NULL
GROUP BY TRUNC(DATE_DEBUT)
ORDER BY DATE_EXEC DESC;

-- =====================================================================
-- 2. FLUX IVALUA - Monitoring imports factures
-- =====================================================================

-- Synthèse quotidienne des imports iValua
SELECT 
    TRUNC(CREATION_DATE) AS DATE_IMPORT,
    COMPANY_VALUE AS SOCIETE,
    COUNT(*) AS NB_FICHIERS,
    SUM(TO_NUMBER(NVL(NB_INVOICES_PROCESSED, '0'))) AS TOTAL_FACTURES_TRAITEES,
    SUM(TO_NUMBER(NVL(NB_INVOICES_REJECTED, '0'))) AS TOTAL_FACTURES_REJETEES,
    ROUND(
        100 * SUM(TO_NUMBER(NVL(NB_INVOICES_REJECTED, '0'))) / 
        NULLIF(SUM(TO_NUMBER(NVL(NB_INVOICES_PROCESSED, '0'))), 0), 
        2
    ) AS TAUX_REJET_PCT,
    COUNT(CASE WHEN STATUS = 'OK' THEN 1 END) AS NB_OK,
    COUNT(CASE WHEN STATUS != 'OK' OR STATUS IS NULL THEN 1 END) AS NB_KO
FROM DKA.DKA_IAPCTRFLUX_IVALUA
WHERE CREATION_DATE >= TRUNC(SYSDATE) - 7
GROUP BY TRUNC(CREATION_DATE), COMPANY_VALUE
ORDER BY DATE_IMPORT DESC, SOCIETE;

-- Détail des imports avec rejets
SELECT 
    NOM_FICHIER,
    TO_CHAR(DATE_ENVOI, 'DD/MM/YYYY HH24:MI:SS') AS DATE_ENVOI,
    COMPANY_VALUE AS SOCIETE,
    TO_NUMBER(NVL(NB_INVOICES_PROCESSED, '0')) AS FAC_TRAITEES,
    TO_NUMBER(NVL(NB_INVOICES_REJECTED, '0')) AS FAC_REJETEES,
    ROUND(
        100 * TO_NUMBER(NVL(NB_INVOICES_REJECTED, '0')) / 
        NULLIF(TO_NUMBER(NVL(NB_INVOICES_PROCESSED, '0')), 0), 
        2
    ) AS TAUX_REJET_PCT,
    STATUS,
    TO_CHAR(CREATION_DATE, 'DD/MM/YYYY HH24:MI:SS') AS DATE_LOG
FROM DKA.DKA_IAPCTRFLUX_IVALUA
WHERE TO_NUMBER(NVL(NB_INVOICES_REJECTED, '0')) > 0
AND CREATION_DATE >= TRUNC(SYSDATE) - 30
ORDER BY DATE_ENVOI DESC;

-- Imports en erreur (STATUS != 'OK')
SELECT 
    NOM_FICHIER,
    TO_CHAR(DATE_ENVOI, 'DD/MM/YYYY HH24:MI:SS') AS DATE_ENVOI,
    COMPANY_VALUE AS SOCIETE,
    STATUS,
    NB_INVOICES_PROCESSED AS FAC_TRAITEES,
    NB_INVOICES_REJECTED AS FAC_REJETEES,
    TO_CHAR(CREATION_DATE, 'DD/MM/YYYY HH24:MI:SS') AS DATE_LOG
FROM DKA.DKA_IAPCTRFLUX_IVALUA
WHERE (STATUS != 'OK' OR STATUS IS NULL)
AND CREATION_DATE >= TRUNC(SYSDATE) - 30
ORDER BY DATE_ENVOI DESC;

-- =====================================================================
-- 3. FLUX AR - Exports factures clients vers EAI
-- =====================================================================

-- Synthèse des exports AR par jour
SELECT 
    TRUNC(CREATION_DATE) AS DATE_EXPORT,
    ORIGIN AS ORIGINE,
    COMPANY_CODE AS CODE_SOCIETE,
    COUNT(*) AS NB_FACTURES_EXPORTEES,
    COUNT(DISTINCT FIC_IDENT) AS NB_FICHIERS,
    MIN(CREATION_DATE) AS PREMIERE_EXPORT,
    MAX(CREATION_DATE) AS DERNIERE_EXPORT
FROM DKA.DKA_SCTLFLUX_ARFLAG_EAI
WHERE CREATION_DATE >= TRUNC(SYSDATE) - 7
GROUP BY TRUNC(CREATION_DATE), ORIGIN, COMPANY_CODE
ORDER BY DATE_EXPORT DESC, ORIGIN, CODE_SOCIETE;

-- Détail avec lien vers concurrent requests Oracle
SELECT 
    DSAE.INVOICE_NUMBER,
    DSAE.ORIGIN,
    DSAE.COMPANY_CODE,
    DSAE.FIC_IDENT,
    TO_CHAR(DSAE.CREATION_DATE, 'DD/MM/YYYY HH24:MI:SS') AS DATE_EXPORT,
    DSAE.REQUEST_ID,
    FCR.CONCURRENT_PROGRAM_ID,
    FCP.CONCURRENT_PROGRAM_NAME,
    FCP.USER_CONCURRENT_PROGRAM_NAME AS PROGRAMME,
    TO_CHAR(FCR.ACTUAL_START_DATE, 'DD/MM/YYYY HH24:MI:SS') AS DEBUT_PROGRAMME,
    TO_CHAR(FCR.ACTUAL_COMPLETION_DATE, 'DD/MM/YYYY HH24:MI:SS') AS FIN_PROGRAMME,
    ROUND((FCR.ACTUAL_COMPLETION_DATE - FCR.ACTUAL_START_DATE) * 24 * 60, 2) AS DUREE_MIN
FROM DKA.DKA_SCTLFLUX_ARFLAG_EAI DSAE
LEFT OUTER JOIN APPLSYS.FND_CONCURRENT_REQUESTS FCR
    ON FCR.REQUEST_ID = DSAE.REQUEST_ID
LEFT OUTER JOIN APPLSYS.FND_CONCURRENT_PROGRAMS_VL FCP
    ON FCP.CONCURRENT_PROGRAM_ID = FCR.CONCURRENT_PROGRAM_ID
WHERE DSAE.CREATION_DATE >= TRUNC(SYSDATE) - 7
ORDER BY DSAE.CREATION_DATE DESC;

-- =====================================================================
-- 4. ANALYSE COMPARATIVE - Performance historique
-- =====================================================================

-- Volumétrie mensuelle EAI (trend)
SELECT 
    TO_CHAR(DATE_DEBUT, 'YYYY-MM') AS MOIS,
    COUNT(*) AS NB_EXECUTIONS,
    SUM(NB_PIECE) AS TOTAL_PIECES,
    ROUND(AVG(NB_PIECE), 0) AS MOY_PIECES_PAR_JOB,
    ROUND(SUM(DEBIT), 2) AS TOTAL_DEBIT,
    ROUND(SUM(CREDIT), 2) AS TOTAL_CREDIT
FROM DKA.DKA_SCTLFLUX_EAI
WHERE DATE_DEBUT >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -6)
GROUP BY TO_CHAR(DATE_DEBUT, 'YYYY-MM')
ORDER BY MOIS DESC;

-- Volumétrie mensuelle iValua (trend)
SELECT 
    TO_CHAR(CREATION_DATE, 'YYYY-MM') AS MOIS,
    COUNT(*) AS NB_FICHIERS,
    SUM(TO_NUMBER(NVL(NB_INVOICES_PROCESSED, '0'))) AS TOTAL_FACTURES,
    ROUND(AVG(TO_NUMBER(NVL(NB_INVOICES_PROCESSED, '0'))), 0) AS MOY_FAC_PAR_FICHIER,
    SUM(TO_NUMBER(NVL(NB_INVOICES_REJECTED, '0'))) AS TOTAL_REJETS,
    ROUND(
        100 * SUM(TO_NUMBER(NVL(NB_INVOICES_REJECTED, '0'))) / 
        NULLIF(SUM(TO_NUMBER(NVL(NB_INVOICES_PROCESSED, '0'))), 0), 
        2
    ) AS TAUX_REJET_PCT
FROM DKA.DKA_IAPCTRFLUX_IVALUA
WHERE CREATION_DATE >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -6)
GROUP BY TO_CHAR(CREATION_DATE, 'YYYY-MM')
ORDER BY MOIS DESC;

-- =====================================================================
-- 5. DIAGNOSTIC - Détection anomalies
-- =====================================================================

-- Jobs EAI jamais terminés (DATE_FIN NULL)
SELECT 
    CODE_FOLIO,
    TO_CHAR(DATE_DEBUT, 'DD/MM/YYYY HH24:MI:SS') AS DEBUT,
    NB_PIECE,
    FICHIER,
    ROUND(SYSDATE - DATE_DEBUT, 2) AS JOURS_ECOULES
FROM DKA.DKA_SCTLFLUX_EAI
WHERE DATE_FIN IS NULL
AND DATE_DEBUT IS NOT NULL
ORDER BY DATE_DEBUT DESC;

-- Jobs EAI anormalement longs (> 2x moyenne)
WITH STATS AS (
    SELECT AVG((DATE_FIN - DATE_DEBUT) * 24 * 60) AS DUREE_MOYENNE
    FROM DKA.DKA_SCTLFLUX_EAI
    WHERE DATE_FIN IS NOT NULL
    AND DATE_DEBUT >= TRUNC(SYSDATE) - 30
)
SELECT 
    E.CODE_FOLIO,
    TO_CHAR(E.DATE_DEBUT, 'DD/MM/YYYY HH24:MI:SS') AS DEBUT,
    ROUND((E.DATE_FIN - E.DATE_DEBUT) * 24 * 60, 2) AS DUREE_MINUTES,
    ROUND(S.DUREE_MOYENNE, 2) AS DUREE_MOYENNE_HABITUELLE,
    E.NB_PIECE,
    E.FICHIER
FROM DKA.DKA_SCTLFLUX_EAI E
CROSS JOIN STATS S
WHERE E.DATE_FIN IS NOT NULL
AND E.DATE_DEBUT >= TRUNC(SYSDATE) - 30
AND (E.DATE_FIN - E.DATE_DEBUT) * 24 * 60 > 2 * S.DUREE_MOYENNE
ORDER BY (E.DATE_FIN - E.DATE_DEBUT) DESC;

-- Imports iValua sans statut
SELECT 
    NOM_FICHIER,
    TO_CHAR(DATE_ENVOI, 'DD/MM/YYYY HH24:MI:SS') AS DATE_ENVOI,
    COMPANY_VALUE,
    NB_INVOICES_PROCESSED,
    TO_CHAR(CREATION_DATE, 'DD/MM/YYYY HH24:MI:SS') AS DATE_LOG
FROM DKA.DKA_IAPCTRFLUX_IVALUA
WHERE STATUS IS NULL
AND CREATION_DATE >= TRUNC(SYSDATE) - 30
ORDER BY CREATION_DATE DESC;

-- =====================================================================
-- 6. AUDIT - Traçabilité utilisateurs
-- =====================================================================

-- Utilisateurs créant des logs (avec nom)
SELECT 
    FU.USER_NAME,
    FU.USER_ID,
    COUNT(*) AS NB_LOGS_CREES,
    MIN(DSE.CREATION_DATE) AS PREMIER_LOG,
    MAX(DSE.CREATION_DATE) AS DERNIER_LOG
FROM DKA.DKA_SCTLFLUX_EAI DSE
JOIN APPLSYS.FND_USER FU ON FU.USER_ID = DSE.CREATED_BY
WHERE DSE.CREATION_DATE >= TRUNC(SYSDATE) - 30
GROUP BY FU.USER_NAME, FU.USER_ID
ORDER BY NB_LOGS_CREES DESC;

-- =====================================================================
-- FIN DES REQUÊTES
-- =====================================================================
