-- =====================================================================
-- Recherche complète - LA CRAU ENERGIES VERTES
-- =====================================================================
-- Date de création : 04/03/2026
-- Base de données : Oracle EBS Production
--
-- OBJECTIF : Extraire toutes les informations du fournisseur "LA CRAU ENERGIES VERTES"
-- incluant les Operating Units, sites, responsabilités, factures, etc.
-- =====================================================================

-- =====================================================================
-- PARTIE 1 : Informations générales du fournisseur
-- =====================================================================
SELECT 
    -- Identification
    APS.VENDOR_ID,
    APS.VENDOR_NAME,
    APS.VENDOR_NAME_ALT,
    APS.SEGMENT1 AS NUMERO_FOURNISSEUR,
    APS.VENDOR_TYPE_LOOKUP_CODE AS TYPE_FOURNISSEUR,
    
    -- Statut
    APS.ENABLED_FLAG AS ACTIF,
    APS.HOLD_FLAG AS EN_ATTENTE,
    APS.HOLD_REASON AS RAISON_ATTENTE,
    APS.HOLD_BY AS MIS_EN_ATTENTE_PAR,
    APS.HOLD_DATE AS DATE_MISE_ATTENTE,
    
    -- Dates
    APS.START_DATE_ACTIVE AS DATE_DEBUT_VALIDITE,
    APS.END_DATE_ACTIVE AS DATE_FIN_VALIDITE,
    APS.CREATION_DATE AS DATE_CREATION,
    APS.LAST_UPDATE_DATE AS DERNIERE_MODIFICATION,
    
    -- Organisation
    APS.ORGANIZATION_TYPE_LOOKUP_CODE AS TYPE_ORGANISATION,
    APS.CUSTOMER_NUM AS NUMERO_CLIENT,
    APS.ONE_TIME_FLAG AS FOURNISSEUR_PONCTUEL,
    
    -- Informations fiscales et monétaires
    APS.PURCHASING_HOLD_REASON AS RAISON_BLOCAGE_ACHAT,
    APS.INVOICE_CURRENCY_CODE AS DEVISE_FACTURE_DEFAUT,
    APS.PAYMENT_CURRENCY_CODE AS DEVISE_PAIEMENT_DEFAUT,
    APS.VAT_REGISTRATION_NUM AS NUMERO_TVA,
    APS.NUM_1099 AS NUMERO_FISCAL,
    
    -- Audit
    APS.CREATED_BY AS CREE_PAR,
    APS.LAST_UPDATED_BY AS MODIFIE_PAR
FROM 
    AP.AP_SUPPLIERS APS
WHERE 
    UPPER(APS.VENDOR_NAME) LIKE '%LA CRAU ENERGIES VERTES%'
ORDER BY 
    APS.VENDOR_NAME;

-- =====================================================================
-- PARTIE 2 : Sites du fournisseur avec Operating Units et termes de paiement
-- =====================================================================
SELECT 
    -- Identification fournisseur
    APS.VENDOR_NAME,
    APS.SEGMENT1 AS NUMERO_FOURNISSEUR,
    APS.VENDOR_ID,
    
    -- Identification site
    APSA.VENDOR_SITE_ID,
    APSA.VENDOR_SITE_CODE AS CODE_SITE,
    APSA.VENDOR_SITE_CODE_ALT AS CODE_SITE_ALTERNATIF,
    
    -- *** OPERATING UNIT ***
    APSA.ORG_ID,
    HOU.NAME AS OPERATING_UNIT,
    HOU.SHORT_CODE AS CODE_OU,
    
    -- Adresse
    APSA.ADDRESS_LINE1 AS ADRESSE_1,
    APSA.ADDRESS_LINE2 AS ADRESSE_2,
    APSA.ADDRESS_LINE3 AS ADRESSE_3,
    APSA.CITY AS VILLE,
    APSA.STATE AS REGION,
    APSA.ZIP AS CODE_POSTAL,
    APSA.COUNTRY AS PAYS,
    
    -- Contact
    APSA.PHONE AS TELEPHONE,
    APSA.FAX AS FAX,
    APSA.EMAIL_ADDRESS AS EMAIL,
    
    -- Statut site
    APSA.INACTIVE_DATE AS DATE_INACTIVATION,
    APSA.HOLD_ALL_PAYMENTS_FLAG AS BLOCAGE_TOUS_PAIEMENTS,
    APSA.HOLD_FUTURE_PAYMENTS_FLAG AS BLOCAGE_PAIEMENTS_FUTURS,
    APSA.HOLD_REASON AS RAISON_BLOCAGE,
    
    -- Termes de paiement
    APSA.TERMS_ID,
    APT.NAME AS NOM_TERME_PAIEMENT,
    APT.DESCRIPTION AS DESCRIPTION_TERME,
    APT.DUE_DAYS AS JOURS_ECHEANCE,
    APT.DISCOUNT_DAYS AS JOURS_ESCOMPTE,
    APT.DISCOUNT_PERCENT AS POURCENTAGE_ESCOMPTE,
    APT.ENABLED_FLAG AS TERME_ACTIF,
    
    -- Options de paiement
    APSA.PAYMENT_METHOD_LOOKUP_CODE AS METHODE_PAIEMENT,
    APSA.PAYMENT_PRIORITY AS PRIORITE_PAIEMENT,
    APSA.PAY_GROUP_LOOKUP_CODE AS GROUPE_PAIEMENT,
    APSA.ALWAYS_TAKE_DISC_FLAG AS TOUJOURS_APPLIQUER_ESCOMPTE,
    APSA.EXCLUDE_FREIGHT_FROM_DISCOUNT AS EXCLURE_FRAIS_PORT_ESCOMPTE,
    
    -- Options fiscales
    APSA.VAT_CODE AS CODE_TVA,
    APSA.ALLOW_AWT_FLAG AS AUTORISER_RETENUE_SOURCE,
    APSA.AWT_GROUP_ID AS GROUPE_RETENUE_SOURCE,
    
    -- Options comptables
    APSA.ACCTS_PAY_CODE_COMBINATION_ID AS COMPTE_FOURNISSEUR,
    GCC1.CONCATENATED_SEGMENTS AS CODE_COMPTABLE_FOURNISSEUR,
    APSA.PREPAY_CODE_COMBINATION_ID AS COMPTE_AVANCE,
    GCC2.CONCATENATED_SEGMENTS AS CODE_COMPTABLE_AVANCE,
    
    -- Options achats et factures
    APSA.PURCHASING_SITE_FLAG AS SITE_ACHATS,
    APSA.PAY_SITE_FLAG AS SITE_PAIEMENT,
    APSA.RFQ_ONLY_SITE_FLAG AS SITE_APPEL_OFFRES_UNIQUEMENT,
    APSA.INVOICE_AMOUNT_LIMIT AS LIMITE_MONTANT_FACTURE,
    APSA.MATCH_OPTION AS OPTION_RAPPROCHEMENT,
    APSA.CREATE_DEBIT_MEMO_FLAG AS CREER_AVOIR,
    
    -- Dates
    APSA.CREATION_DATE AS DATE_CREATION_SITE,
    APSA.LAST_UPDATE_DATE AS DERNIERE_MODIFICATION_SITE,
    
    -- Audit
    APSA.CREATED_BY AS SITE_CREE_PAR,
    APSA.LAST_UPDATED_BY AS SITE_MODIFIE_PAR
    
FROM 
    AP.AP_SUPPLIERS APS
    INNER JOIN AP.AP_SUPPLIER_SITES_ALL APSA 
        ON APS.VENDOR_ID = APSA.VENDOR_ID
    LEFT OUTER JOIN HR.HR_OPERATING_UNITS HOU 
        ON APSA.ORG_ID = HOU.ORGANIZATION_ID
    LEFT OUTER JOIN AP.AP_TERMS APT 
        ON APSA.TERMS_ID = APT.TERM_ID
    LEFT OUTER JOIN GL.GL_CODE_COMBINATIONS_KFV GCC1
        ON APSA.ACCTS_PAY_CODE_COMBINATION_ID = GCC1.CODE_COMBINATION_ID
    LEFT OUTER JOIN GL.GL_CODE_COMBINATIONS_KFV GCC2
        ON APSA.PREPAY_CODE_COMBINATION_ID = GCC2.CODE_COMBINATION_ID
WHERE 
    UPPER(APS.VENDOR_NAME) LIKE '%LA CRAU ENERGIES VERTES%'
ORDER BY 
    APS.VENDOR_NAME, 
    HOU.NAME,
    APSA.VENDOR_SITE_CODE;

-- =====================================================================
-- PARTIE 3 : Contacts du fournisseur
-- =====================================================================
SELECT 
    APS.VENDOR_NAME,
    APS.SEGMENT1 AS NUMERO_FOURNISSEUR,
    APC.VENDOR_CONTACT_ID,
    APC.FIRST_NAME AS PRENOM,
    APC.LAST_NAME AS NOM,
    APC.TITLE AS TITRE,
    APC.DEPARTMENT AS DEPARTEMENT,
    APC.PHONE AS TELEPHONE,
    APC.ALT_PHONE AS TELEPHONE_ALTERNATIF,
    APC.FAX AS FAX,
    APC.EMAIL_ADDRESS AS EMAIL,
    APC.URL AS SITE_WEB,
    APC.INACTIVE_DATE AS DATE_INACTIVATION,
    APC.CREATION_DATE AS DATE_CREATION,
    APC.LAST_UPDATE_DATE AS DERNIERE_MODIFICATION
FROM 
    AP.AP_SUPPLIERS APS
    LEFT OUTER JOIN AP.AP_SUPPLIER_CONTACTS APC 
        ON APS.VENDOR_ID = APC.VENDOR_ID
WHERE 
    UPPER(APS.VENDOR_NAME) LIKE '%LA CRAU ENERGIES VERTES%'
ORDER BY 
    APS.VENDOR_NAME, 
    APC.LAST_NAME, 
    APC.FIRST_NAME;

-- =====================================================================
-- PARTIE 4 : Comptes bancaires du fournisseur
-- =====================================================================
SELECT 
    APS.VENDOR_NAME,
    APS.SEGMENT1 AS NUMERO_FOURNISSEUR,
    IEBA.EXT_BANK_ACCOUNT_ID,
    IEBA.BANK_ACCOUNT_NAME AS NOM_COMPTE,
    IEBA.BANK_ACCOUNT_NUM AS NUMERO_COMPTE,
    IEBA.BANK_ACCOUNT_TYPE AS TYPE_COMPTE,
    IEBA.IBAN AS IBAN,
    IEBA.CHECK_DIGITS AS CLE_RIB,
    IEBA.CURRENCY_CODE AS DEVISE,
    IEBA.ACCOUNT_SUFFIX AS SUFFIXE_COMPTE,
    IEBA.DESCRIPTION AS DESCRIPTION,
    IEBA.COUNTRY_CODE AS CODE_PAYS,
    IEBA.BRANCH_ID,
    IEBB.BRANCH_NAME AS NOM_AGENCE,
    IEBB.BRANCH_NUMBER AS NUMERO_AGENCE,
    IEBB.BIC AS CODE_BIC_SWIFT,
    IEBB.BANK_NAME AS NOM_BANQUE,
    IEBB.BANK_NUMBER AS NUMERO_BANQUE,
    IEBA.START_DATE AS DATE_DEBUT_VALIDITE,
    IEBA.END_DATE AS DATE_FIN_VALIDITE,
    IEBA.CREATION_DATE AS DATE_CREATION,
    IEBA.LAST_UPDATE_DATE AS DERNIERE_MODIFICATION
FROM 
    AP.AP_SUPPLIERS APS
    INNER JOIN IBY.IBY_EXTERNAL_PAYEES_ALL IEPA 
        ON APS.VENDOR_ID = IEPA.PAYEE_PARTY_ID 
        AND IEPA.PAYMENT_FUNCTION = 'PAYABLES_DISB'
        AND IEPA.PARTY_SITE_ID IS NULL
    INNER JOIN IBY.IBY_PMT_INSTR_USES_ALL IPIA 
        ON IEPA.EXT_PAYEE_ID = IPIA.EXT_PMT_PARTY_ID
    INNER JOIN IBY.IBY_EXT_BANK_ACCOUNTS IEBA 
        ON IPIA.INSTRUMENT_ID = IEBA.EXT_BANK_ACCOUNT_ID
    LEFT OUTER JOIN CE.CE_BANK_BRANCHES_V IEBB 
        ON IEBA.BRANCH_ID = IEBB.BRANCH_PARTY_ID
WHERE 
    UPPER(APS.VENDOR_NAME) LIKE '%LA CRAU ENERGIES VERTES%'
    AND (IEBA.END_DATE IS NULL OR IEBA.END_DATE > SYSDATE)
ORDER BY 
    APS.VENDOR_NAME, 
    IEBA.BANK_ACCOUNT_NAME;

-- =====================================================================
-- PARTIE 5 : Factures du fournisseur (2025-2026)
-- =====================================================================
SELECT 
    APS.VENDOR_NAME,
    APS.SEGMENT1 AS NUMERO_FOURNISSEUR,
    HOU.NAME AS OPERATING_UNIT,
    AIA.INVOICE_ID,
    AIA.INVOICE_NUM AS NUMERO_FACTURE,
    AIA.INVOICE_DATE AS DATE_FACTURE,
    AIA.INVOICE_AMOUNT AS MONTANT_FACTURE,
    AIA.INVOICE_CURRENCY_CODE AS DEVISE,
    AIA.GL_DATE AS DATE_COMPTABLE,
    AIA.PAYMENT_STATUS_FLAG AS STATUT_PAIEMENT,
    DECODE(AIA.PAYMENT_STATUS_FLAG, 
        'N', 'IMPAYÉE', 
        'P', 'PARTIELLEMENT PAYÉE', 
        'Y', 'PAYÉE') AS STATUT_PAIEMENT_LIBELLE,
    AIA.AMOUNT_PAID AS MONTANT_PAYE,
    AIA.CANCELLED_DATE AS DATE_ANNULATION,
    AIA.CREATION_DATE AS DATE_CREATION,
    AIA.LAST_UPDATE_DATE AS DERNIERE_MODIFICATION,
    APSA.VENDOR_SITE_CODE AS SITE_FOURNISSEUR,
    AIA.DESCRIPTION AS DESCRIPTION_FACTURE,
    AIA.SOURCE AS SOURCE
FROM 
    AP.AP_SUPPLIERS APS
    INNER JOIN AP.AP_INVOICES_ALL AIA 
        ON APS.VENDOR_ID = AIA.VENDOR_ID
    LEFT OUTER JOIN AP.AP_SUPPLIER_SITES_ALL APSA 
        ON AIA.VENDOR_SITE_ID = APSA.VENDOR_SITE_ID
    LEFT OUTER JOIN HR.HR_OPERATING_UNITS HOU 
        ON AIA.ORG_ID = HOU.ORGANIZATION_ID
WHERE 
    UPPER(APS.VENDOR_NAME) LIKE '%LA CRAU ENERGIES VERTES%'
    AND AIA.INVOICE_DATE >= TO_DATE('01/01/2025', 'DD/MM/YYYY')
ORDER BY 
    AIA.INVOICE_DATE DESC,
    AIA.INVOICE_NUM;

-- =====================================================================
-- PARTIE 6 : Statistiques des factures par Operating Unit
-- =====================================================================
SELECT 
    APS.VENDOR_NAME,
    HOU.NAME AS OPERATING_UNIT,
    EXTRACT(YEAR FROM AIA.INVOICE_DATE) AS ANNEE,
    EXTRACT(MONTH FROM AIA.INVOICE_DATE) AS MOIS,
    COUNT(*) AS NOMBRE_FACTURES,
    SUM(AIA.INVOICE_AMOUNT) AS TOTAL_FACTURES,
    SUM(CASE WHEN AIA.PAYMENT_STATUS_FLAG = 'Y' THEN AIA.INVOICE_AMOUNT ELSE 0 END) AS TOTAL_PAYE,
    SUM(CASE WHEN AIA.PAYMENT_STATUS_FLAG = 'N' THEN AIA.INVOICE_AMOUNT ELSE 0 END) AS TOTAL_IMPAYE,
    AIA.INVOICE_CURRENCY_CODE AS DEVISE
FROM 
    AP.AP_SUPPLIERS APS
    INNER JOIN AP.AP_INVOICES_ALL AIA 
        ON APS.VENDOR_ID = AIA.VENDOR_ID
    LEFT OUTER JOIN HR.HR_OPERATING_UNITS HOU 
        ON AIA.ORG_ID = HOU.ORGANIZATION_ID
WHERE 
    UPPER(APS.VENDOR_NAME) LIKE '%LA CRAU ENERGIES VERTES%'
    AND AIA.INVOICE_DATE >= TO_DATE('01/01/2025', 'DD/MM/YYYY')
    AND AIA.CANCELLED_DATE IS NULL
GROUP BY 
    APS.VENDOR_NAME,
    HOU.NAME,
    EXTRACT(YEAR FROM AIA.INVOICE_DATE),
    EXTRACT(MONTH FROM AIA.INVOICE_DATE),
    AIA.INVOICE_CURRENCY_CODE
ORDER BY 
    HOU.NAME,
    ANNEE DESC,
    MOIS DESC;

-- =====================================================================
-- PARTIE 7 : Bons de commande liés au fournisseur
-- =====================================================================
SELECT 
    APS.VENDOR_NAME,
    APS.SEGMENT1 AS NUMERO_FOURNISSEUR,
    HOU.NAME AS OPERATING_UNIT,
    PHA.SEGMENT1 AS NUMERO_BC,
    PHA.PO_HEADER_ID,
    PHA.TYPE_LOOKUP_CODE AS TYPE_BC,
    PHA.AUTHORIZATION_STATUS AS STATUT_AUTORISATION,
    PHA.APPROVED_FLAG AS APPROUVE,
    PHA.CLOSED_CODE AS CODE_FERMETURE,
    PHA.CANCEL_FLAG AS ANNULE,
    PHA.CREATION_DATE AS DATE_CREATION,
    PHA.APPROVED_DATE AS DATE_APPROBATION,
    PHA.CURRENCY_CODE AS DEVISE,
    (SELECT SUM(PLA.QUANTITY * PLA.UNIT_PRICE)
     FROM PO.PO_LINES_ALL PLA
     WHERE PLA.PO_HEADER_ID = PHA.PO_HEADER_ID) AS MONTANT_TOTAL_BC
FROM 
    AP.AP_SUPPLIERS APS
    INNER JOIN PO.PO_HEADERS_ALL PHA
        ON APS.VENDOR_ID = PHA.VENDOR_ID
    LEFT OUTER JOIN HR.HR_OPERATING_UNITS HOU 
        ON PHA.ORG_ID = HOU.ORGANIZATION_ID
WHERE 
    UPPER(APS.VENDOR_NAME) LIKE '%LA CRAU ENERGIES VERTES%'
ORDER BY 
    PHA.CREATION_DATE DESC;

-- =====================================================================
-- PARTIE 8 : Responsabilités AP/PO pour les Operating Units du fournisseur
-- =====================================================================
-- Cette requête liste les responsabilités liées aux modules AP (Accounts Payable)
-- et PO (Purchase Orders) pour les Operating Units où le fournisseur est référencé
SELECT DISTINCT
    HOU.NAME AS OPERATING_UNIT,
    HOU.ORGANIZATION_ID AS ORG_ID,
    FR.RESPONSIBILITY_NAME AS RESPONSABILITE,
    FR.RESPONSIBILITY_KEY AS CLE_RESPONSABILITE,
    FA.APPLICATION_NAME AS MODULE,
    FR.START_DATE AS DATE_DEBUT,
    FR.END_DATE AS DATE_FIN
FROM 
    AP.AP_SUPPLIERS APS
    INNER JOIN AP.AP_SUPPLIER_SITES_ALL APSA 
        ON APS.VENDOR_ID = APSA.VENDOR_ID
    INNER JOIN HR.HR_OPERATING_UNITS HOU 
        ON APSA.ORG_ID = HOU.ORGANIZATION_ID
    CROSS JOIN FND_RESPONSIBILITY_VL FR
    INNER JOIN FND_APPLICATION_VL FA
        ON FR.APPLICATION_ID = FA.APPLICATION_ID
WHERE 
    UPPER(APS.VENDOR_NAME) LIKE '%LA CRAU ENERGIES VERTES%'
    AND FA.APPLICATION_SHORT_NAME IN ('PO', 'AP', 'SQLAP')
    AND (HOU.SHORT_CODE IS NULL 
         OR UPPER(FR.RESPONSIBILITY_NAME) LIKE '%' || UPPER(TRIM(TO_CHAR(HOU.SHORT_CODE))) || '%')
    AND (FR.END_DATE IS NULL OR FR.END_DATE > SYSDATE)
ORDER BY 
    HOU.NAME,
    FA.APPLICATION_NAME,
    FR.RESPONSIBILITY_NAME;

-- =====================================================================
-- PARTIE 9 : Utilisateurs ayant accès aux responsabilités AP/PO 
--           pour les Operating Units du fournisseur
-- =====================================================================
SELECT DISTINCT
    HOU.NAME AS OPERATING_UNIT,
    FU.USER_NAME AS MATRICULE,
    FU.DESCRIPTION AS NOM_UTILISATEUR,
    FU.EMAIL_ADDRESS AS EMAIL_UTILISATEUR,
    FR.RESPONSIBILITY_NAME AS RESPONSABILITE,
    FA.APPLICATION_NAME AS MODULE,
    FURG.START_DATE AS DATE_DEBUT_AFFECTATION,
    FURG.END_DATE AS DATE_FIN_AFFECTATION
FROM 
    AP.AP_SUPPLIERS APS
    INNER JOIN AP.AP_SUPPLIER_SITES_ALL APSA 
        ON APS.VENDOR_ID = APSA.VENDOR_ID
    INNER JOIN HR.HR_OPERATING_UNITS HOU 
        ON APSA.ORG_ID = HOU.ORGANIZATION_ID
    CROSS JOIN FND_RESPONSIBILITY_VL FR
    INNER JOIN FND_APPLICATION_VL FA
        ON FR.APPLICATION_ID = FA.APPLICATION_ID
    INNER JOIN FND_USER_RESP_GROUPS_DIRECT FURG
        ON FR.RESPONSIBILITY_ID = FURG.RESPONSIBILITY_ID
        AND FR.APPLICATION_ID = FURG.RESPONSIBILITY_APPLICATION_ID
    INNER JOIN FND_USER FU
        ON FURG.USER_ID = FU.USER_ID
WHERE 
    UPPER(APS.VENDOR_NAME) LIKE '%LA CRAU ENERGIES VERTES%'
    AND FA.APPLICATION_SHORT_NAME IN ('PO', 'AP', 'SQLAP')
    AND (HOU.SHORT_CODE IS NULL 
         OR UPPER(FR.RESPONSIBILITY_NAME) LIKE '%' || UPPER(TRIM(TO_CHAR(HOU.SHORT_CODE))) || '%')
    AND (FR.END_DATE IS NULL OR FR.END_DATE > SYSDATE)
    AND (FURG.END_DATE IS NULL OR FURG.END_DATE > SYSDATE)
    AND (FU.END_DATE IS NULL OR FU.END_DATE > SYSDATE)
ORDER BY 
    HOU.NAME,
    FU.USER_NAME,
    FA.APPLICATION_NAME,
    FR.RESPONSIBILITY_NAME;
