-- =====================================================================
-- Recherche des Responsabilités pour ORG_ID = 86
-- =====================================================================
-- Date de création : 04/03/2026
-- Base de données : Oracle EBS Production
--
-- OBJECTIF : Extraire toutes les responsabilités liées à l'org_id 86
-- =====================================================================

-- =====================================================================
-- PARTIE 1 : Informations sur l'Operating Unit (org_id = 86)
-- =====================================================================
SELECT 
    HOU.ORGANIZATION_ID AS ORG_ID,
    HOU.NAME AS OPERATING_UNIT,
    HOU.SHORT_CODE AS CODE_OU,
    HOU.DATE_FROM AS DATE_DEBUT,
    HOU.DATE_TO AS DATE_FIN,
    HOU.INTERNAL_EXTERNAL_FLAG AS TYPE_ORG,
    HOU.SET_OF_BOOKS_ID AS LEDGER_ID,
    GL.NAME AS LEDGER_NAME,
    GL.CURRENCY_CODE AS DEVISE
FROM 
    HR.HR_OPERATING_UNITS HOU
    LEFT JOIN GL.GL_LEDGERS GL 
        ON HOU.SET_OF_BOOKS_ID = GL.LEDGER_ID
WHERE 
    HOU.ORGANIZATION_ID = 86;

-- =====================================================================
-- PARTIE 2 : Toutes les responsabilités liées à l'org_id 86
-- =====================================================================
-- Recherche basée sur le code OU dans le nom de la responsabilité
SELECT 
    FR.RESPONSIBILITY_ID,
    FR.RESPONSIBILITY_KEY AS CLE_RESPONSABILITE,
    FR.RESPONSIBILITY_NAME AS NOM_RESPONSABILITE,
    FA.APPLICATION_NAME AS MODULE,
    FA.APPLICATION_SHORT_NAME AS CODE_MODULE,
    FR.DESCRIPTION AS DESCRIPTION,
    FR.START_DATE AS DATE_DEBUT,
    FR.END_DATE AS DATE_FIN,
    FR.MENU_ID,
    FR.VERSION AS VERSION,
    FR.WEB_HOST_NAME,
    FR.WEB_AGENT_NAME
FROM 
    HR.HR_OPERATING_UNITS HOU
    CROSS JOIN APPS.FND_RESPONSIBILITY_VL FR
    INNER JOIN APPS.FND_APPLICATION_VL FA
        ON FR.APPLICATION_ID = FA.APPLICATION_ID
WHERE 
    HOU.ORGANIZATION_ID = 86
    AND (
        FR.RESPONSIBILITY_NAME LIKE '%' || HOU.SHORT_CODE || '%'
        OR FR.RESPONSIBILITY_KEY LIKE '%' || HOU.SHORT_CODE || '%'
    )
    AND (FR.END_DATE IS NULL OR FR.END_DATE > SYSDATE)
ORDER BY 
    FA.APPLICATION_NAME,
    FR.RESPONSIBILITY_NAME;

-- =====================================================================
-- PARTIE 3 : Responsabilités AP (Accounts Payable) pour org_id 86
-- =====================================================================
SELECT 
    HOU.NAME AS OPERATING_UNIT,
    FR.RESPONSIBILITY_ID,
    FR.RESPONSIBILITY_NAME AS NOM_RESPONSABILITE,
    FR.RESPONSIBILITY_KEY AS CLE_RESPONSABILITE,
    FR.START_DATE AS DATE_DEBUT,
    FR.END_DATE AS DATE_FIN
FROM 
    HR.HR_OPERATING_UNITS HOU
    CROSS JOIN APPS.FND_RESPONSIBILITY_VL FR
    INNER JOIN APPS.FND_APPLICATION_VL FA
        ON FR.APPLICATION_ID = FA.APPLICATION_ID
WHERE 
    HOU.ORGANIZATION_ID = 86
    AND FA.APPLICATION_SHORT_NAME IN ('AP', 'SQLAP')
    AND (
        FR.RESPONSIBILITY_NAME LIKE '%' || HOU.SHORT_CODE || '%'
        OR FR.RESPONSIBILITY_KEY LIKE '%' || HOU.SHORT_CODE || '%'
    )
    AND (FR.END_DATE IS NULL OR FR.END_DATE > SYSDATE)
ORDER BY 
    FR.RESPONSIBILITY_NAME;

-- =====================================================================
-- PARTIE 4 : Responsabilités PO (Purchase Orders) pour org_id 86
-- =====================================================================
SELECT 
    HOU.NAME AS OPERATING_UNIT,
    FR.RESPONSIBILITY_ID,
    FR.RESPONSIBILITY_NAME AS NOM_RESPONSABILITE,
    FR.RESPONSIBILITY_KEY AS CLE_RESPONSABILITE,
    FR.START_DATE AS DATE_DEBUT,
    FR.END_DATE AS DATE_FIN
FROM 
    HR.HR_OPERATING_UNITS HOU
    CROSS JOIN APPS.FND_RESPONSIBILITY_VL FR
    INNER JOIN APPS.FND_APPLICATION_VL FA
        ON FR.APPLICATION_ID = FA.APPLICATION_ID
WHERE 
    HOU.ORGANIZATION_ID = 86
    AND FA.APPLICATION_SHORT_NAME = 'PO'
    AND (
        FR.RESPONSIBILITY_NAME LIKE '%' || HOU.SHORT_CODE || '%'
        OR FR.RESPONSIBILITY_KEY LIKE '%' || HOU.SHORT_CODE || '%'
    )
    AND (FR.END_DATE IS NULL OR FR.END_DATE > SYSDATE)
ORDER BY 
    FR.RESPONSIBILITY_NAME;

-- =====================================================================
-- PARTIE 5 : Responsabilités GL (General Ledger) pour org_id 86
-- =====================================================================
SELECT 
    HOU.NAME AS OPERATING_UNIT,
    FR.RESPONSIBILITY_ID,
    FR.RESPONSIBILITY_NAME AS NOM_RESPONSABILITE,
    FR.RESPONSIBILITY_KEY AS CLE_RESPONSABILITE,
    FR.START_DATE AS DATE_DEBUT,
    FR.END_DATE AS DATE_FIN
FROM 
    HR.HR_OPERATING_UNITS HOU
    CROSS JOIN APPS.FND_RESPONSIBILITY_VL FR
    INNER JOIN APPS.FND_APPLICATION_VL FA
        ON FR.APPLICATION_ID = FA.APPLICATION_ID
WHERE 
    HOU.ORGANIZATION_ID = 86
    AND FA.APPLICATION_SHORT_NAME IN ('GL', 'SQLGL')
    AND (
        FR.RESPONSIBILITY_NAME LIKE '%' || HOU.SHORT_CODE || '%'
        OR FR.RESPONSIBILITY_KEY LIKE '%' || HOU.SHORT_CODE || '%'
    )
    AND (FR.END_DATE IS NULL OR FR.END_DATE > SYSDATE)
ORDER BY 
    FR.RESPONSIBILITY_NAME;

-- =====================================================================
-- PARTIE 6 : Responsabilités AR (Accounts Receivable) pour org_id 86
-- =====================================================================
SELECT 
    HOU.NAME AS OPERATING_UNIT,
    FR.RESPONSIBILITY_ID,
    FR.RESPONSIBILITY_NAME AS NOM_RESPONSABILITE,
    FR.RESPONSIBILITY_KEY AS CLE_RESPONSABILITE,
    FR.START_DATE AS DATE_DEBUT,
    FR.END_DATE AS DATE_FIN
FROM 
    HR.HR_OPERATING_UNITS HOU
    CROSS JOIN APPS.FND_RESPONSIBILITY_VL FR
    INNER JOIN APPS.FND_APPLICATION_VL FA
        ON FR.APPLICATION_ID = FA.APPLICATION_ID
WHERE 
    HOU.ORGANIZATION_ID = 86
    AND FA.APPLICATION_SHORT_NAME IN ('AR', 'SQLAR')
    AND (
        FR.RESPONSIBILITY_NAME LIKE '%' || HOU.SHORT_CODE || '%'
        OR FR.RESPONSIBILITY_KEY LIKE '%' || HOU.SHORT_CODE || '%'
    )
    AND (FR.END_DATE IS NULL OR FR.END_DATE > SYSDATE)
ORDER BY 
    FR.RESPONSIBILITY_NAME;

-- =====================================================================
-- PARTIE 7 : Utilisateurs ayant accès aux responsabilités de l'org_id 86
-- =====================================================================
SELECT 
    HOU.NAME AS OPERATING_UNIT,
    FU.USER_NAME AS MATRICULE,
    FU.DESCRIPTION AS NOM_UTILISATEUR,
    FU.EMAIL_ADDRESS AS EMAIL,
    FR.RESPONSIBILITY_NAME AS RESPONSABILITE,
    FA.APPLICATION_NAME AS MODULE,
    FURG.START_DATE AS DATE_DEBUT_AFFECTATION,
    FURG.END_DATE AS DATE_FIN_AFFECTATION,
    DECODE(FU.END_DATE, NULL, 'ACTIF', 'INACTIF') AS STATUT_UTILISATEUR
FROM 
    HR.HR_OPERATING_UNITS HOU
    CROSS JOIN APPS.FND_RESPONSIBILITY_VL FR
    INNER JOIN APPS.FND_APPLICATION_VL FA
        ON FR.APPLICATION_ID = FA.APPLICATION_ID
    INNER JOIN APPS.FND_USER_RESP_GROUPS_DIRECT FURG
        ON FR.RESPONSIBILITY_ID = FURG.RESPONSIBILITY_ID
        AND FR.APPLICATION_ID = FURG.RESPONSIBILITY_APPLICATION_ID
    INNER JOIN APPS.FND_USER FU
        ON FURG.USER_ID = FU.USER_ID
WHERE 
    HOU.ORGANIZATION_ID = 86
    AND (
        FR.RESPONSIBILITY_NAME LIKE '%' || HOU.SHORT_CODE || '%'
        OR FR.RESPONSIBILITY_KEY LIKE '%' || HOU.SHORT_CODE || '%'
    )
    AND (FR.END_DATE IS NULL OR FR.END_DATE > SYSDATE)
    AND (FURG.END_DATE IS NULL OR FURG.END_DATE > SYSDATE)
ORDER BY 
    FA.APPLICATION_NAME,
    FR.RESPONSIBILITY_NAME,
    FU.USER_NAME;

-- =====================================================================
-- PARTIE 8 : Comptage des utilisateurs par responsabilité
-- =====================================================================
SELECT 
    HOU.NAME AS OPERATING_UNIT,
    FA.APPLICATION_NAME AS MODULE,
    FR.RESPONSIBILITY_NAME AS RESPONSABILITE,
    COUNT(DISTINCT FU.USER_ID) AS NOMBRE_UTILISATEURS,
    COUNT(DISTINCT CASE WHEN FU.END_DATE IS NULL OR FU.END_DATE > SYSDATE 
          THEN FU.USER_ID END) AS UTILISATEURS_ACTIFS
FROM 
    HR.HR_OPERATING_UNITS HOU
    CROSS JOIN APPS.FND_RESPONSIBILITY_VL FR
    INNER JOIN APPS.FND_APPLICATION_VL FA
        ON FR.APPLICATION_ID = FA.APPLICATION_ID
    LEFT JOIN APPS.FND_USER_RESP_GROUPS_DIRECT FURG
        ON FR.RESPONSIBILITY_ID = FURG.RESPONSIBILITY_ID
        AND FR.APPLICATION_ID = FURG.RESPONSIBILITY_APPLICATION_ID
        AND (FURG.END_DATE IS NULL OR FURG.END_DATE > SYSDATE)
    LEFT JOIN APPS.FND_USER FU
        ON FURG.USER_ID = FU.USER_ID
WHERE 
    HOU.ORGANIZATION_ID = 86
    AND (
        FR.RESPONSIBILITY_NAME LIKE '%' || HOU.SHORT_CODE || '%'
        OR FR.RESPONSIBILITY_KEY LIKE '%' || HOU.SHORT_CODE || '%'
    )
    AND (FR.END_DATE IS NULL OR FR.END_DATE > SYSDATE)
GROUP BY 
    HOU.NAME,
    FA.APPLICATION_NAME,
    FR.RESPONSIBILITY_NAME
ORDER BY 
    FA.APPLICATION_NAME,
    NOMBRE_UTILISATEURS DESC,
    FR.RESPONSIBILITY_NAME;

-- =====================================================================
-- PARTIE 9 : Recherche alternative - Toutes responsabilités contenant "DEW"
-- =====================================================================
-- Si le code OU commence par "DEW", cette requête trouvera toutes les 
-- responsabilités associées
SELECT 
    FR.RESPONSIBILITY_ID,
    FR.RESPONSIBILITY_NAME AS NOM_RESPONSABILITE,
    FR.RESPONSIBILITY_KEY AS CLE_RESPONSABILITE,
    FA.APPLICATION_NAME AS MODULE,
    FA.APPLICATION_SHORT_NAME AS CODE_MODULE,
    FR.START_DATE AS DATE_DEBUT,
    FR.END_DATE AS DATE_FIN,
    COUNT(DISTINCT FURG.USER_ID) AS NOMBRE_UTILISATEURS
FROM 
    APPS.FND_RESPONSIBILITY_VL FR
    INNER JOIN APPS.FND_APPLICATION_VL FA
        ON FR.APPLICATION_ID = FA.APPLICATION_ID
    LEFT JOIN APPS.FND_USER_RESP_GROUPS_DIRECT FURG
        ON FR.RESPONSIBILITY_ID = FURG.RESPONSIBILITY_ID
        AND FR.APPLICATION_ID = FURG.RESPONSIBILITY_APPLICATION_ID
        AND (FURG.END_DATE IS NULL OR FURG.END_DATE > SYSDATE)
WHERE 
    (FR.RESPONSIBILITY_NAME LIKE '%DEW%' OR FR.RESPONSIBILITY_KEY LIKE '%DEW%')
    AND (FR.END_DATE IS NULL OR FR.END_DATE > SYSDATE)
GROUP BY 
    FR.RESPONSIBILITY_ID,
    FR.RESPONSIBILITY_NAME,
    FR.RESPONSIBILITY_KEY,
    FA.APPLICATION_NAME,
    FA.APPLICATION_SHORT_NAME,
    FR.START_DATE,
    FR.END_DATE
ORDER BY 
    FA.APPLICATION_NAME,
    FR.RESPONSIBILITY_NAME;

-- =====================================================================
-- PARTIE 10 : Sites fournisseurs dans l'org_id 86
-- =====================================================================
SELECT 
    HOU.NAME AS OPERATING_UNIT,
    HOU.ORGANIZATION_ID AS ORG_ID,
    COUNT(DISTINCT APSA.VENDOR_ID) AS NOMBRE_FOURNISSEURS,
    COUNT(DISTINCT APSA.VENDOR_SITE_ID) AS NOMBRE_SITES,
    COUNT(DISTINCT CASE WHEN APSA.INACTIVE_DATE IS NULL 
          THEN APSA.VENDOR_SITE_ID END) AS SITES_ACTIFS,
    COUNT(DISTINCT CASE WHEN APSA.PURCHASING_SITE_FLAG = 'Y' 
          THEN APSA.VENDOR_SITE_ID END) AS SITES_ACHAT,
    COUNT(DISTINCT CASE WHEN APSA.PAY_SITE_FLAG = 'Y' 
          THEN APSA.VENDOR_SITE_ID END) AS SITES_PAIEMENT
FROM 
    HR.HR_OPERATING_UNITS HOU
    LEFT JOIN AP.AP_SUPPLIER_SITES_ALL APSA
        ON HOU.ORGANIZATION_ID = APSA.ORG_ID
WHERE 
    HOU.ORGANIZATION_ID = 86
GROUP BY 
    HOU.NAME,
    HOU.ORGANIZATION_ID;
