-- =====================================================================
-- Extraction des Dépenses - Code GS0211082R - Société 348
-- =====================================================================
-- Date de création : 15/12/2025
-- Base de données : Oracle EBS 12.2.13 (Database 19.25.0.0.0)
-- Organisation : 348 (DSW0497)
-- Code recherché : GS0211082R (dans tous les segments analytiques)
--
-- DESCRIPTION :
-- Cette requête extrait toutes les dépenses (factures fournisseurs et 
-- écritures GL) pour le code GS0211082R de la société 348.
-- =====================================================================

-- =====================================================================
-- PARTIE 1 : FACTURES FOURNISSEURS (AP)
-- =====================================================================

SELECT 
    'AP_INVOICE' AS SOURCE_TYPE,
    AIA.INVOICE_NUM,
    AIA.INVOICE_DATE,
    AIA.GL_DATE,
    AIA.INVOICE_CURRENCY_CODE AS DEVISE,
    DECODE(AIA.PAYMENT_STATUS_FLAG, 'N', 'NON PAYÉ', 'P', 'Partiellement Payé', 'Y', 'PAYÉ') AS STATUT_PAIEMENT,
    APS.VENDOR_NAME AS FOURNISSEUR,
    APS.SEGMENT1 AS NUM_FOURNISSEUR,
    APSS.VENDOR_SITE_CODE AS SITE_FOURNISSEUR,
    PHA.SEGMENT1 AS NUM_COMMANDE,
    AIA.INVOICE_AMOUNT AS MONTANT_FACTURE,
    AIDA.AMOUNT AS MONTANT_LIGNE,
    AIDA.LINE_TYPE_LOOKUP_CODE AS TYPE_LIGNE,
    GCC.CONCATENATED_SEGMENTS AS CODE_COMPTABLE,
    GCC.SEGMENT1 AS ENTITE,
    GCC.SEGMENT2 AS COMPTE,
    GCC.SEGMENT3 AS COST_CENTER,
    GCC.SEGMENT4 AS PROJET,
    GCC.SEGMENT5 AS ACTIVITE,
    GCC.SEGMENT6 AS INTERCO,
    GCC.SEGMENT7 AS RESERVE,
    AIDA.DESCRIPTION AS DESCRIPTION_DISTRIBUTION,
    AIA.DESCRIPTION AS DESCRIPTION_FACTURE,
    ACA.CHECK_NUMBER AS NUM_CHEQUE,
    AIPA.AMOUNT AS MONTANT_PAIEMENT,
    APSA.AMOUNT_REMAINING AS MONTANT_RESTANT,
    HOU.NAME AS ORGANISATION,
    GL.NAME AS LEDGER,
    AIA.CREATION_DATE,
    FU.USER_NAME AS CREATEUR
FROM 
    AP.AP_INVOICES_ALL AIA
    INNER JOIN AP.AP_INVOICE_LINES_ALL AILA ON AIA.INVOICE_ID = AILA.INVOICE_ID
    INNER JOIN AP.AP_INVOICE_DISTRIBUTIONS_ALL AIDA ON AILA.INVOICE_ID = AIDA.INVOICE_ID 
        AND AILA.LINE_NUMBER = AIDA.INVOICE_LINE_NUMBER
    INNER JOIN GL.GL_CODE_COMBINATIONS_KFV GCC ON AIDA.DIST_CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
    INNER JOIN AP.AP_SUPPLIERS APS ON AIA.VENDOR_ID = APS.VENDOR_ID
    INNER JOIN AP.AP_SUPPLIER_SITES_ALL APSS ON AIA.VENDOR_SITE_ID = APSS.VENDOR_SITE_ID 
        AND APS.VENDOR_ID = APSS.VENDOR_ID
    LEFT JOIN PO.PO_HEADERS_ALL PHA ON AIA.PO_HEADER_ID = PHA.PO_HEADER_ID
    LEFT JOIN AP.AP_INVOICE_PAYMENTS_ALL AIPA ON AIPA.INVOICE_ID = AIA.INVOICE_ID
    LEFT JOIN AP.AP_CHECKS_ALL ACA ON ACA.CHECK_ID = AIPA.CHECK_ID
    LEFT JOIN AP.AP_PAYMENT_SCHEDULES_ALL APSA ON APSA.INVOICE_ID = AIA.INVOICE_ID
    LEFT JOIN HR_OPERATING_UNITS HOU ON HOU.ORGANIZATION_ID = AIA.ORG_ID
    LEFT JOIN GL.GL_LEDGERS GL ON GL.LEDGER_ID = AIA.SET_OF_BOOKS_ID
    LEFT JOIN APPS.FND_USER FU ON AIA.CREATED_BY = FU.USER_ID
WHERE 
    AIA.ORG_ID = 348
    AND GCC.SEGMENT1 = '0348'
    AND (
        GCC.SEGMENT2 = 'GS0211082R'
        OR GCC.SEGMENT3 = 'GS0211082R'
        OR GCC.SEGMENT4 = 'GS0211082R'
        OR GCC.SEGMENT5 = 'GS0211082R'
        OR GCC.SEGMENT6 = 'GS0211082R'
        OR GCC.SEGMENT7 = 'GS0211082R'
    )

UNION ALL

-- =====================================================================
-- PARTIE 2 : ÉCRITURES GL (Grand Livre)
-- =====================================================================

SELECT 
    'GL_JOURNAL' AS SOURCE_TYPE,
    GJH.NAME AS INVOICE_NUM,
    GJH.DEFAULT_EFFECTIVE_DATE AS INVOICE_DATE,
    GJH.DEFAULT_EFFECTIVE_DATE AS GL_DATE,
    GJH.CURRENCY_CODE AS DEVISE,
    GJH.STATUS AS STATUT_PAIEMENT,
    NULL AS FOURNISSEUR,
    NULL AS NUM_FOURNISSEUR,
    NULL AS SITE_FOURNISSEUR,
    NULL AS NUM_COMMANDE,
    NULL AS MONTANT_FACTURE,
    (NVL(GJL.ACCOUNTED_DR, 0) - NVL(GJL.ACCOUNTED_CR, 0)) AS MONTANT_LIGNE,
    'GL_JOURNAL' AS TYPE_LIGNE,
    GCC.CONCATENATED_SEGMENTS AS CODE_COMPTABLE,
    GCC.SEGMENT1 AS ENTITE,
    GCC.SEGMENT2 AS COMPTE,
    GCC.SEGMENT3 AS COST_CENTER,
    GCC.SEGMENT4 AS PROJET,
    GCC.SEGMENT5 AS ACTIVITE,
    GCC.SEGMENT6 AS INTERCO,
    GCC.SEGMENT7 AS RESERVE,
    GJL.DESCRIPTION AS DESCRIPTION_DISTRIBUTION,
    GJH.DESCRIPTION AS DESCRIPTION_FACTURE,
    NULL AS NUM_CHEQUE,
    NULL AS MONTANT_PAIEMENT,
    NULL AS MONTANT_RESTANT,
    NULL AS ORGANISATION,
    GLE.NAME AS LEDGER,
    GJL.CREATION_DATE,
    FU.USER_NAME AS CREATEUR
FROM 
    GL.GL_JE_LINES GJL
    INNER JOIN GL.GL_JE_HEADERS GJH ON GJL.JE_HEADER_ID = GJH.JE_HEADER_ID
    INNER JOIN GL.GL_CODE_COMBINATIONS_KFV GCC ON GJL.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
    INNER JOIN GL.GL_LEDGERS GLE ON GLE.LEDGER_ID = GJL.LEDGER_ID
    LEFT JOIN APPS.FND_USER FU ON GJL.CREATED_BY = FU.USER_ID
WHERE 
    GCC.SEGMENT1 = '0348'
    AND (
        GCC.SEGMENT2 = 'GS0211082R'
        OR GCC.SEGMENT3 = 'GS0211082R'
        OR GCC.SEGMENT4 = 'GS0211082R'
        OR GCC.SEGMENT5 = 'GS0211082R'
        OR GCC.SEGMENT6 = 'GS0211082R'
        OR GCC.SEGMENT7 = 'GS0211082R'
    )
    AND GJH.STATUS = 'P'  -- Seulement les journaux comptabilisés

ORDER BY 
    INVOICE_DATE DESC,
    SOURCE_TYPE,
    CREATION_DATE DESC;

-- =====================================================================
-- STATISTIQUES RAPIDES
-- =====================================================================

-- Décommenter pour avoir un résumé des montants par segment
/*
SELECT 
    CASE 
        WHEN GCC.SEGMENT2 = 'GS0211082R' THEN 'SEGMENT2-COMPTE'
        WHEN GCC.SEGMENT3 = 'GS0211082R' THEN 'SEGMENT3-COST_CENTER'
        WHEN GCC.SEGMENT4 = 'GS0211082R' THEN 'SEGMENT4-PROJET'
        WHEN GCC.SEGMENT5 = 'GS0211082R' THEN 'SEGMENT5-ACTIVITE'
        WHEN GCC.SEGMENT6 = 'GS0211082R' THEN 'SEGMENT6-INTERCO'
        WHEN GCC.SEGMENT7 = 'GS0211082R' THEN 'SEGMENT7-RESERVE'
    END AS SEGMENT_TROUVE,
    COUNT(*) AS NB_LIGNES,
    SUM(AIDA.AMOUNT) AS MONTANT_TOTAL,
    MIN(AIA.INVOICE_DATE) AS DATE_PREMIERE_FACTURE,
    MAX(AIA.INVOICE_DATE) AS DATE_DERNIERE_FACTURE
FROM 
    AP.AP_INVOICES_ALL AIA
    INNER JOIN AP.AP_INVOICE_DISTRIBUTIONS_ALL AIDA ON AIA.INVOICE_ID = AIDA.INVOICE_ID
    INNER JOIN GL.GL_CODE_COMBINATIONS_KFV GCC ON AIDA.DIST_CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
WHERE 
    AIA.ORG_ID = 348
    AND GCC.SEGMENT1 = '0348'
    AND (
        GCC.SEGMENT2 = 'GS0211082R'
        OR GCC.SEGMENT3 = 'GS0211082R'
        OR GCC.SEGMENT4 = 'GS0211082R'
        OR GCC.SEGMENT5 = 'GS0211082R'
        OR GCC.SEGMENT6 = 'GS0211082R'
        OR GCC.SEGMENT7 = 'GS0211082R'
    )
GROUP BY 
    CASE 
        WHEN GCC.SEGMENT2 = 'GS0211082R' THEN 'SEGMENT2-COMPTE'
        WHEN GCC.SEGMENT3 = 'GS0211082R' THEN 'SEGMENT3-COST_CENTER'
        WHEN GCC.SEGMENT4 = 'GS0211082R' THEN 'SEGMENT4-PROJET'
        WHEN GCC.SEGMENT5 = 'GS0211082R' THEN 'SEGMENT5-ACTIVITE'
        WHEN GCC.SEGMENT6 = 'GS0211082R' THEN 'SEGMENT6-INTERCO'
        WHEN GCC.SEGMENT7 = 'GS0211082R' THEN 'SEGMENT7-RESERVE'
    END;
*/
