-- =====================================================================
-- Recherche complète - Fournisseur "Groupe services france"
-- =====================================================================
-- Date de création : 30/12/2025
-- Base de données : Oracle EBS Production
--
-- OBJECTIF : Extraire toutes les informations du fournisseur
-- incluant les termes de paiement, sites, statuts, etc.
-- =====================================================================

-- =====================================================================
-- PARTIE 1 : Informations générales du fournisseur
-- =====================================================================
SELECT 
    -- Identification
    APS.VENDOR_ID,
    APS.VENDOR_NAME,
    APS.VENDOR_NAME_ALT,
    APS.SEGMENT1 AS NUMERO_FOURNISSEUR,
    APS.VENDOR_TYPE_LOOKUP_CODE AS TYPE_FOURNISSEUR,
    
    -- Statut
    APS.ENABLED_FLAG AS ACTIF,
    APS.HOLD_FLAG AS EN_ATTENTE,
    APS.HOLD_REASON AS RAISON_ATTENTE,
    APS.HOLD_BY AS MIS_EN_ATTENTE_PAR,
    APS.HOLD_DATE AS DATE_MISE_ATTENTE,
    
    -- Dates
    APS.START_DATE_ACTIVE AS DATE_DEBUT_VALIDITE,
    APS.END_DATE_ACTIVE AS DATE_FIN_VALIDITE,
    APS.CREATION_DATE AS DATE_CREATION,
    APS.LAST_UPDATE_DATE AS DERNIERE_MODIFICATION,
    
    -- Organisation
    APS.ORGANIZATION_TYPE_LOOKUP_CODE AS TYPE_ORGANISATION,
    APS.CUSTOMER_NUM AS NUMERO_CLIENT,
    APS.ONE_TIME_FLAG AS FOURNISSEUR_PONCTUEL,
    
    -- Contact
    APS.PURCHASING_HOLD_REASON AS RAISON_BLOCAGE_ACHAT,
    APS.INVOICE_CURRENCY_CODE AS DEVISE_FACTURE_DEFAUT,
    APS.PAYMENT_CURRENCY_CODE AS DEVISE_PAIEMENT_DEFAUT,
    APS.VAT_REGISTRATION_NUM AS NUMERO_TVA,
    APS.NUM_1099 AS NUMERO_FISCAL,
    
    -- Audit
    APS.CREATED_BY AS CREE_PAR,
    APS.LAST_UPDATED_BY AS MODIFIE_PAR
FROM 
    AP.AP_SUPPLIERS APS
WHERE 
    UPPER(APS.VENDOR_NAME) LIKE UPPER('%Groupe services france%')
ORDER BY 
    APS.VENDOR_NAME;

-- =====================================================================
-- PARTIE 2 : Sites du fournisseur avec termes de paiement
-- =====================================================================
SELECT 
    -- Identification fournisseur
    APS.VENDOR_NAME,
    APS.SEGMENT1 AS NUMERO_FOURNISSEUR,
    
    -- Identification site
    APSA.VENDOR_SITE_ID,
    APSA.VENDOR_SITE_CODE AS CODE_SITE,
    APSA.VENDOR_SITE_CODE_ALT AS CODE_SITE_ALTERNATIF,
    
    -- Organisation
    APSA.ORG_ID,
    HOU.NAME AS ORGANISATION,
    
    -- Adresse
    APSA.ADDRESS_LINE1 AS ADRESSE_1,
    APSA.ADDRESS_LINE2 AS ADRESSE_2,
    APSA.ADDRESS_LINE3 AS ADRESSE_3,
    APSA.CITY AS VILLE,
    APSA.STATE AS REGION,
    APSA.ZIP AS CODE_POSTAL,
    APSA.COUNTRY AS PAYS,
    
    -- Contact
    APSA.PHONE AS TELEPHONE,
    APSA.FAX AS FAX,
    APSA.EMAIL_ADDRESS AS EMAIL,
    
    -- Statut site
    APSA.INACTIVE_DATE AS DATE_INACTIVATION,
    APSA.HOLD_ALL_PAYMENTS_FLAG AS BLOCAGE_TOUS_PAIEMENTS,
    APSA.HOLD_FUTURE_PAYMENTS_FLAG AS BLOCAGE_PAIEMENTS_FUTURS,
    APSA.HOLD_REASON AS RAISON_BLOCAGE,
    
    -- Termes de paiement
    APSA.TERMS_ID,
    APT.NAME AS NOM_TERME_PAIEMENT,
    APT.DESCRIPTION AS DESCRIPTION_TERME,
    APT.DUE_DAYS AS JOURS_ECHEANCE,
    APT.DISCOUNT_DAYS AS JOURS_ESCOMPTE,
    APT.DISCOUNT_PERCENT AS POURCENTAGE_ESCOMPTE,
    APT.ENABLED_FLAG AS TERME_ACTIF,
    
    -- Options de paiement
    APSA.PAYMENT_METHOD_LOOKUP_CODE AS METHODE_PAIEMENT,
    APSA.PAYMENT_PRIORITY AS PRIORITE_PAIEMENT,
    APSA.PAY_GROUP_LOOKUP_CODE AS GROUPE_PAIEMENT,
    APSA.ALWAYS_TAKE_DISC_FLAG AS TOUJOURS_APPLIQUER_ESCOMPTE,
    APSA.EXCLUDE_FREIGHT_FROM_DISCOUNT AS EXCLURE_FRAIS_PORT_ESCOMPTE,
    
    -- Options fiscales
    APSA.VAT_CODE AS CODE_TVA,
    APSA.ALLOW_AWT_FLAG AS AUTORISER_RETENUE_SOURCE,
    APSA.AWT_GROUP_ID AS GROUPE_RETENUE_SOURCE,
    
    -- Options comptables
    APSA.ACCTS_PAY_CODE_COMBINATION_ID AS COMPTE_FOURNISSEUR,
    APSA.PREPAY_CODE_COMBINATION_ID AS COMPTE_AVANCE,
    APSA.LIABILITY_DISTRIBUTION_ID AS DISTRIBUTION_PASSIF,
    
    -- Options achats
    APSA.PURCHASING_SITE_FLAG AS SITE_ACHATS,
    APSA.PAY_SITE_FLAG AS SITE_PAIEMENT,
    APSA.RFQ_ONLY_SITE_FLAG AS SITE_APPEL_OFFRES_UNIQUEMENT,
    
    -- Options factures
    APSA.INVOICE_AMOUNT_LIMIT AS LIMITE_MONTANT_FACTURE,
    APSA.MATCH_OPTION AS OPTION_RAPPROCHEMENT,
    APSA.CREATE_DEBIT_MEMO_FLAG AS CREER_AVOIR,
    
    -- Dates
    APSA.CREATION_DATE AS DATE_CREATION_SITE,
    APSA.LAST_UPDATE_DATE AS DERNIERE_MODIFICATION_SITE,
    
    -- Audit
    APSA.CREATED_BY AS SITE_CREE_PAR,
    APSA.LAST_UPDATED_BY AS SITE_MODIFIE_PAR
    
FROM 
    AP.AP_SUPPLIERS APS
    INNER JOIN AP.AP_SUPPLIER_SITES_ALL APSA 
        ON APS.VENDOR_ID = APSA.VENDOR_ID
    LEFT OUTER JOIN HR.HR_OPERATING_UNITS HOU 
        ON APSA.ORG_ID = HOU.ORGANIZATION_ID
    LEFT OUTER JOIN AP.AP_TERMS APT 
        ON APSA.TERMS_ID = APT.TERM_ID
WHERE 
    UPPER(APS.VENDOR_NAME) LIKE UPPER('%Groupe services france%')
ORDER BY 
    APS.VENDOR_NAME, 
    APSA.ORG_ID, 
    APSA.VENDOR_SITE_CODE;

-- =====================================================================
-- PARTIE 3 : Contacts du fournisseur
-- =====================================================================
SELECT 
    APS.VENDOR_NAME,
    APS.SEGMENT1 AS NUMERO_FOURNISSEUR,
    APC.VENDOR_CONTACT_ID,
    APC.FIRST_NAME AS PRENOM,
    APC.MIDDLE_NAME AS SECOND_PRENOM,
    APC.LAST_NAME AS NOM,
    APC.TITLE AS TITRE,
    APC.DEPARTMENT AS DEPARTEMENT,
    APC.MAIL_STOP AS SERVICE_COURRIER,
    APC.AREA_CODE AS INDICATIF_ZONE,
    APC.PHONE AS TELEPHONE,
    APC.FAX AS FAX,
    APC.FAX_AREA_CODE AS INDICATIF_FAX,
    APC.EMAIL_ADDRESS AS EMAIL,
    APC.URL AS SITE_WEB,
    APC.INACTIVE_DATE AS DATE_INACTIVATION,
    APC.CREATION_DATE AS DATE_CREATION,
    APC.LAST_UPDATE_DATE AS DERNIERE_MODIFICATION
FROM 
    AP.AP_SUPPLIERS APS
    LEFT OUTER JOIN AP.AP_SUPPLIER_CONTACTS APC 
        ON APS.VENDOR_ID = APC.VENDOR_ID
WHERE 
    UPPER(APS.VENDOR_NAME) LIKE UPPER('%Groupe services france%')
ORDER BY 
    APS.VENDOR_NAME, 
    APC.LAST_NAME, 
    APC.FIRST_NAME;

-- =====================================================================
-- PARTIE 4 : Comptes bancaires du fournisseur
-- =====================================================================
SELECT 
    APS.VENDOR_NAME,
    APS.SEGMENT1 AS NUMERO_FOURNISSEUR,
    IEBA.EXT_BANK_ACCOUNT_ID,
    IEBA.BANK_ACCOUNT_NAME AS NOM_COMPTE,
    IEBA.BANK_ACCOUNT_NUM AS NUMERO_COMPTE,
    IEBA.BANK_ACCOUNT_TYPE AS TYPE_COMPTE,
    IEBA.IBAN AS IBAN,
    IEBA.CHECK_DIGITS AS CLE_RIB,
    IEBA.CURRENCY_CODE AS DEVISE,
    IEBA.ACCOUNT_SUFFIX AS SUFFIXE_COMPTE,
    IEBA.DESCRIPTION AS DESCRIPTION,
    IEBA.COUNTRY_CODE AS CODE_PAYS,
    IEBA.BRANCH_ID,
    IEBB.BRANCH_NAME AS NOM_AGENCE,
    IEBB.BRANCH_NUMBER AS NUMERO_AGENCE,
    IEBB.BIC AS CODE_BIC_SWIFT,
    IEBB.BANK_NAME AS NOM_BANQUE,
    IEBB.BANK_NUMBER AS NUMERO_BANQUE,
    IEBA.START_DATE AS DATE_DEBUT_VALIDITE,
    IEBA.END_DATE AS DATE_FIN_VALIDITE,
    IEBA.CREATION_DATE AS DATE_CREATION,
    IEBA.LAST_UPDATE_DATE AS DERNIERE_MODIFICATION
FROM 
    AP.AP_SUPPLIERS APS
    INNER JOIN IBY.IBY_EXTERNAL_PAYEES_ALL IEPA 
        ON APS.VENDOR_ID = IEPA.SUPPLIER_PARTY_ID
        AND IEPA.PARTY_SITE_ID IS NULL
        AND IEPA.SUPPLIER_SITE_ID IS NULL
    INNER JOIN IBY.IBY_PMT_INSTR_USES_ALL IPIUA 
        ON IEPA.EXT_PAYEE_ID = IPIUA.EXT_PMT_PARTY_ID
    INNER JOIN IBY.IBY_EXT_BANK_ACCOUNTS IEBA 
        ON IPIUA.INSTRUMENT_ID = IEBA.EXT_BANK_ACCOUNT_ID
    LEFT OUTER JOIN AP.AP_BANK_BRANCHES IBB 
        ON IEBA.BRANCH_ID = IBB.BANK_BRANCH_ID
    LEFT OUTER JOIN IBY.IBY_EXT_BANK_BRANCHES IEBB 
        ON IEBA.BRANCH_ID = IEBB.BRANCH_PARTY_ID
WHERE 
    UPPER(APS.VENDOR_NAME) LIKE UPPER('%Groupe services france%')
    AND IEBA.END_DATE IS NULL
ORDER BY 
    APS.VENDOR_NAME, 
    IEBA.BANK_ACCOUNT_NAME;

-- =====================================================================
-- PARTIE 5 : Statistiques des factures
-- =====================================================================
SELECT 
    APS.VENDOR_NAME,
    APS.SEGMENT1 AS NUMERO_FOURNISSEUR,
    COUNT(DISTINCT AIA.INVOICE_ID) AS NOMBRE_FACTURES,
    COUNT(DISTINCT CASE WHEN AIA.PAYMENT_STATUS_FLAG = 'Y' THEN AIA.INVOICE_ID END) AS FACTURES_PAYEES,
    COUNT(DISTINCT CASE WHEN AIA.PAYMENT_STATUS_FLAG = 'N' THEN AIA.INVOICE_ID END) AS FACTURES_NON_PAYEES,
    COUNT(DISTINCT CASE WHEN AIA.CANCELLED_DATE IS NOT NULL THEN AIA.INVOICE_ID END) AS FACTURES_ANNULEES,
    MIN(AIA.INVOICE_DATE) AS DATE_PREMIERE_FACTURE,
    MAX(AIA.INVOICE_DATE) AS DATE_DERNIERE_FACTURE,
    SUM(AIA.INVOICE_AMOUNT) AS MONTANT_TOTAL_FACTURES,
    SUM(CASE WHEN AIA.PAYMENT_STATUS_FLAG = 'N' THEN AIA.INVOICE_AMOUNT ELSE 0 END) AS MONTANT_IMPAYE,
    AIA.INVOICE_CURRENCY_CODE AS DEVISE
FROM 
    AP.AP_SUPPLIERS APS
    LEFT OUTER JOIN AP.AP_INVOICES_ALL AIA 
        ON APS.VENDOR_ID = AIA.VENDOR_ID
WHERE 
    UPPER(APS.VENDOR_NAME) LIKE UPPER('%Groupe services france%')
GROUP BY 
    APS.VENDOR_NAME,
    APS.SEGMENT1,
    AIA.INVOICE_CURRENCY_CODE
ORDER BY 
    APS.VENDOR_NAME,
    AIA.INVOICE_CURRENCY_CODE;

-- =====================================================================
-- PARTIE 6 : Dernières factures (10 dernières)
-- =====================================================================
SELECT * FROM (
    SELECT 
        APS.VENDOR_NAME,
        APS.SEGMENT1 AS NUMERO_FOURNISSEUR,
        AIA.INVOICE_NUM AS NUMERO_FACTURE,
        AIA.INVOICE_DATE AS DATE_FACTURE,
        AIA.INVOICE_AMOUNT AS MONTANT_FACTURE,
        AIA.INVOICE_CURRENCY_CODE AS DEVISE,
        AIA.PAYMENT_STATUS_FLAG AS PAYEE,
        AIA.CANCELLED_DATE AS DATE_ANNULATION,
        AIA.GL_DATE AS DATE_COMPTABLE,
        AIA.CREATION_DATE AS DATE_CREATION,
        AIA.LAST_UPDATE_DATE AS DERNIERE_MODIFICATION,
        APSA.VENDOR_SITE_CODE AS SITE_FOURNISSEUR,
        HOU.NAME AS ORGANISATION
    FROM 
        AP.AP_SUPPLIERS APS
        INNER JOIN AP.AP_INVOICES_ALL AIA 
            ON APS.VENDOR_ID = AIA.VENDOR_ID
        LEFT OUTER JOIN AP.AP_SUPPLIER_SITES_ALL APSA 
            ON AIA.VENDOR_SITE_ID = APSA.VENDOR_SITE_ID
        LEFT OUTER JOIN HR.HR_OPERATING_UNITS HOU 
            ON AIA.ORG_ID = HOU.ORGANIZATION_ID
    WHERE 
        UPPER(APS.VENDOR_NAME) LIKE UPPER('%Groupe services france%')
    ORDER BY 
        AIA.INVOICE_DATE DESC
)
WHERE ROWNUM <= 10;

-- =====================================================================
-- PARTIE 7 : Historique des paiements (10 derniers)
-- =====================================================================
SELECT * FROM (
    SELECT 
        APS.VENDOR_NAME,
        APS.SEGMENT1 AS NUMERO_FOURNISSEUR,
        AIA.INVOICE_NUM AS NUMERO_FACTURE,
        AIP.CHECK_ID,
        AIP.AMOUNT AS MONTANT_PAIEMENT,
        AC.CHECK_NUMBER AS NUMERO_CHEQUE,
        AC.CHECK_DATE AS DATE_CHEQUE,
        AC.CLEARED_DATE AS DATE_ENCAISSEMENT,
        AC.VOID_DATE AS DATE_ANNULATION,
        AC.PAYMENT_METHOD_CODE AS METHODE_PAIEMENT,
        AC.CURRENCY_CODE AS DEVISE,
        AC.STATUS_LOOKUP_CODE AS STATUT
    FROM 
        AP.AP_SUPPLIERS APS
        INNER JOIN AP.AP_INVOICES_ALL AIA 
            ON APS.VENDOR_ID = AIA.VENDOR_ID
        INNER JOIN AP.AP_INVOICE_PAYMENTS_ALL AIP 
            ON AIA.INVOICE_ID = AIP.INVOICE_ID
        INNER JOIN AP.AP_CHECKS_ALL AC 
            ON AIP.CHECK_ID = AC.CHECK_ID
    WHERE 
        UPPER(APS.VENDOR_NAME) LIKE UPPER('%Groupe services france%')
    ORDER BY 
        AC.CHECK_DATE DESC
)
WHERE ROWNUM <= 10;
