WHENEVER SQLERROR EXIT SQL.SQLCODE
SET ECHO OFF
SET FEEDBACK ON
SET TIMING ON
SET TERMOUT OFF
@c:/Users/schibout/Documents/plsql/OptimisationRequete/FACTURES_EN_COURS_V2_Q1.sql
SET TERMOUT ON
PROMPT QUERY_DONE
EXIT
