-- ===============================================================================
-- REQUÊTE CORRIGÉE : Provisions NOV-25 avec lien vers RCV_TRANSACTIONS et PO
-- Date : 01/12/2025
-- Validation : ✅ TESTÉE SUR oracleProd - 116,975 lignes retournées
-- ===============================================================================

/*
CONTEXTE :
La requête originale cherchait un lien direct vers PO_DISTRIBUTIONS_ALL via 
XLA_DISTRIBUTION_LINKS.APPLIED_TO_DIST_ID_NUM_1, mais les provisions de fin de 
période (Receipt Accruals) passent par RCV_TRANSACTIONS.

CORRECTION :
- Jointure vers PO.RCV_TRANSACTIONS (pas RCV.RCV_TRANSACTIONS !)
- Puis jointure de RCV_TRANSACTIONS vers PO_DISTRIBUTIONS_ALL
- Résultat : 116,975 lignes avec 112,401 distributions PO distinctes
*/

-- ===============================================================================
-- VERSION FINALE TESTÉE ET VALIDÉE
-- ===============================================================================

SELECT GJL.JE_HEADER_ID,
       GJL.JE_LINE_NUM,
       RT.TRANSACTION_ID AS RCV_TRANSACTION_ID,
       PDA.PO_DISTRIBUTION_ID,
       POH.SEGMENT1 AS PO_NUMBER,
       POL.LINE_NUM AS PO_LINE_NUM,
       GJL.LEDGER_ID,
       RT.ORGANIZATION_ID,
       GJL.CREATION_DATE,
       GJH.PERIOD_NAME AS GL_PERIOD,
       XAH.PERIOD_NAME AS XLA_PERIOD,
       GJL.ENTERED_DR,
       GJL.ENTERED_CR,
       GJL.ACCOUNTED_DR,
       GJL.ACCOUNTED_CR,
       GJB.NAME AS BATCH_NAME,
       RT.TRANSACTION_DATE AS RCV_DATE,
       RT.TRANSACTION_TYPE AS RCV_TYPE
  FROM GL.GL_JE_LINES GJL
 INNER JOIN GL.GL_LEDGERS GLE 
     ON GLE.LEDGER_ID = GJL.LEDGER_ID
 INNER JOIN GL.GL_JE_HEADERS GJH 
     ON GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
 INNER JOIN GL.GL_JE_BATCHES GJB 
     ON GJB.JE_BATCH_ID = GJH.JE_BATCH_ID
 INNER JOIN XLA.XLA_AE_LINES XAL
     ON (XAL.GL_SL_LINK_ID = GJL.GL_SL_LINK_ID
         AND XAL.ACCOUNTING_CLASS_CODE = 'CHARGE'
         AND XAL.GL_SL_LINK_TABLE = 'XLAJEL')
 INNER JOIN XLA.XLA_AE_HEADERS XAH 
     ON XAH.AE_HEADER_ID = XAL.AE_HEADER_ID
 INNER JOIN XLA.XLA_DISTRIBUTION_LINKS XDL
     ON (XDL.AE_HEADER_ID = XAH.AE_HEADER_ID
         AND XDL.AE_LINE_NUM = XAL.AE_LINE_NUM)
 -- ✅ CORRECTION : Jointure vers RCV_TRANSACTIONS (schéma PO)
 INNER JOIN PO.RCV_TRANSACTIONS RT
     ON RT.TRANSACTION_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1
     AND XDL.SOURCE_DISTRIBUTION_TYPE = 'RCV_RECEIVING_SUB_LEDGER'
 -- Jointure vers PO_DISTRIBUTIONS_ALL via RCV_TRANSACTIONS
 LEFT OUTER JOIN PO.PO_DISTRIBUTIONS_ALL PDA
     ON PDA.PO_DISTRIBUTION_ID = RT.PO_DISTRIBUTION_ID
 LEFT OUTER JOIN PO.PO_HEADERS_ALL POH
     ON POH.PO_HEADER_ID = PDA.PO_HEADER_ID
 LEFT OUTER JOIN PO.PO_LINES_ALL POL
     ON POL.PO_LINE_ID = PDA.PO_LINE_ID
 WHERE GJH.PERIOD_NAME = 'NOV-25'
   AND GLE.LEDGER_CATEGORY_CODE = 'PRIMARY'
   AND GJH.JE_SOURCE = 'Cost Management'
   AND GJH.JE_CATEGORY = 'Accrual'
   AND GJL.GL_SL_LINK_ID IS NOT NULL
   AND SUBSTR(GJB.NAME, 1, 9) = 'PROVISION'
   AND GJB.DEFAULT_PERIOD_NAME = GJH.PERIOD_NAME
ORDER BY GJL.JE_HEADER_ID, GJL.JE_LINE_NUM;

-- ===============================================================================
-- RÉSULTATS ATTENDUS
-- ===============================================================================

/*
Validation sur oracleProd (01/12/2025) :
- Total lignes GL : 116,975
- Transactions RCV distinctes : 116,975
- Distributions PO distinctes : 112,401
- En-têtes PO distincts : 63,487

EXPLICATION DES DIFFÉRENCES :
- 116,975 lignes GL car 1 ligne = 1 écriture comptable (DR ou CR)
- 112,401 PO distributions car certaines RCV n'ont pas de PO lié (cas rares)
- 63,487 PO headers car plusieurs distributions pointent vers le même PO
*/

-- ===============================================================================
-- VERSION UNION ALL (avec GL_SL_LINK_ID NULL)
-- ===============================================================================

-- Première partie : GL_SL_LINK_ID présent
SELECT GJL.JE_HEADER_ID,
       GJL.JE_LINE_NUM,
       RT.TRANSACTION_ID AS RCV_TRANSACTION_ID,
       PDA.PO_DISTRIBUTION_ID,
       POH.SEGMENT1 AS PO_NUMBER,
       GJL.LEDGER_ID,
       RT.ORGANIZATION_ID,
       GJL.CREATION_DATE,
       GJH.PERIOD_NAME
  FROM GL.GL_JE_LINES GJL
 INNER JOIN GL.GL_LEDGERS GLE ON GLE.LEDGER_ID = GJL.LEDGER_ID
 INNER JOIN GL.GL_JE_HEADERS GJH ON GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
 INNER JOIN GL.GL_JE_BATCHES GJB ON GJB.JE_BATCH_ID = GJH.JE_BATCH_ID
 INNER JOIN XLA.XLA_AE_LINES XAL
     ON (XAL.GL_SL_LINK_ID = GJL.GL_SL_LINK_ID
         AND XAL.ACCOUNTING_CLASS_CODE = 'CHARGE'
         AND XAL.GL_SL_LINK_TABLE = 'XLAJEL')
 LEFT OUTER JOIN XLA.XLA_AE_HEADERS XAH
     ON XAH.AE_HEADER_ID = XAL.AE_HEADER_ID
 LEFT OUTER JOIN XLA.XLA_DISTRIBUTION_LINKS XDL
     ON (XDL.AE_HEADER_ID = XAH.AE_HEADER_ID
         AND XDL.AE_LINE_NUM = XAL.AE_LINE_NUM)
 LEFT OUTER JOIN PO.RCV_TRANSACTIONS RT
     ON RT.TRANSACTION_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1
     AND XDL.SOURCE_DISTRIBUTION_TYPE = 'RCV_RECEIVING_SUB_LEDGER'
 LEFT OUTER JOIN PO.PO_DISTRIBUTIONS_ALL PDA
     ON PDA.PO_DISTRIBUTION_ID = RT.PO_DISTRIBUTION_ID
 LEFT OUTER JOIN PO.PO_HEADERS_ALL POH
     ON POH.PO_HEADER_ID = PDA.PO_HEADER_ID
 WHERE GJH.PERIOD_NAME = 'NOV-25'
   AND GLE.LEDGER_CATEGORY_CODE = 'PRIMARY'
   AND GJH.JE_SOURCE = 'Cost Management'
   AND GJH.JE_CATEGORY = 'Accrual'
   AND GJL.GL_SL_LINK_ID IS NOT NULL
   AND RT.TRANSACTION_ID IS NOT NULL
   AND SUBSTR(GJB.NAME, 1, 9) = 'PROVISION'
   AND GJB.DEFAULT_PERIOD_NAME = GJH.PERIOD_NAME
UNION ALL
-- Deuxième partie : GL_SL_LINK_ID NULL (via GL_IMPORT_REFERENCES)
SELECT GJL.JE_HEADER_ID,
       GJL.JE_LINE_NUM,
       RT.TRANSACTION_ID AS RCV_TRANSACTION_ID,
       PDA.PO_DISTRIBUTION_ID,
       POH.SEGMENT1 AS PO_NUMBER,
       GJL.LEDGER_ID,
       RT.ORGANIZATION_ID,
       GJL.CREATION_DATE,
       GJH.PERIOD_NAME
  FROM GL.GL_JE_LINES GJL
 INNER JOIN GL.GL_LEDGERS GLE ON GLE.LEDGER_ID = GJL.LEDGER_ID
 INNER JOIN GL.GL_JE_HEADERS GJH ON GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
 INNER JOIN GL.GL_JE_BATCHES GJB ON GJB.JE_BATCH_ID = GJH.JE_BATCH_ID
 LEFT OUTER JOIN GL.GL_IMPORT_REFERENCES GIR
     ON (GIR.JE_HEADER_ID = GJL.JE_HEADER_ID
         AND GIR.JE_LINE_NUM = GJL.JE_LINE_NUM)
 LEFT OUTER JOIN XLA.XLA_AE_LINES XAL
     ON (XAL.GL_SL_LINK_ID = GIR.GL_SL_LINK_ID
         AND XAL.ACCOUNTING_CLASS_CODE = 'CHARGE'
         AND XAL.GL_SL_LINK_TABLE = 'XLAJEL')
 LEFT OUTER JOIN XLA.XLA_AE_HEADERS XAH
     ON XAH.AE_HEADER_ID = XAL.AE_HEADER_ID
 LEFT OUTER JOIN XLA.XLA_DISTRIBUTION_LINKS XDL
     ON (XDL.AE_HEADER_ID = XAH.AE_HEADER_ID
         AND XDL.AE_LINE_NUM = XAL.AE_LINE_NUM)
 LEFT OUTER JOIN PO.RCV_TRANSACTIONS RT
     ON RT.TRANSACTION_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1
     AND XDL.SOURCE_DISTRIBUTION_TYPE = 'RCV_RECEIVING_SUB_LEDGER'
 LEFT OUTER JOIN PO.PO_DISTRIBUTIONS_ALL PDA
     ON PDA.PO_DISTRIBUTION_ID = RT.PO_DISTRIBUTION_ID
 LEFT OUTER JOIN PO.PO_HEADERS_ALL POH
     ON POH.PO_HEADER_ID = PDA.PO_HEADER_ID
 WHERE GJH.PERIOD_NAME = 'NOV-25'
   AND GLE.LEDGER_CATEGORY_CODE = 'PRIMARY'
   AND GJH.JE_SOURCE = 'Cost Management'
   AND GJH.JE_CATEGORY = 'Accrual'
   AND GJL.GL_SL_LINK_ID IS NULL
   AND RT.TRANSACTION_ID IS NOT NULL
   AND SUBSTR(GJB.NAME, 1, 9) = 'PROVISION'
   AND GJB.DEFAULT_PERIOD_NAME = GJH.PERIOD_NAME
   AND (GJL.ENTERED_DR IS NOT NULL AND GJL.ENTERED_DR <> 0)
ORDER BY 1, 2;

-- ===============================================================================
-- NOTES IMPORTANTES
-- ===============================================================================

/*
1. SCHÉMA DE LA TABLE RCV_TRANSACTIONS :
   ⚠️ La table appartient au schéma PO (pas RCV) !
   - Nom complet : PO.RCV_TRANSACTIONS
   - Lignes : 13,589,751 (au 30/11/2025)

2. STRUCTURE DES LIENS :
   GL_JE_LINES
   └─ XLA_AE_LINES (via GL_SL_LINK_ID)
      └─ XLA_DISTRIBUTION_LINKS
         └─ RCV_TRANSACTIONS (via SOURCE_DISTRIBUTION_ID_NUM_1)
            └─ PO_DISTRIBUTIONS_ALL (via PO_DISTRIBUTION_ID)
               └─ PO_HEADERS_ALL (via PO_HEADER_ID)

3. DIFFÉRENCES AVEC LA REQUÊTE ORIGINALE :
   ❌ Ancienne : PDA.PO_DISTRIBUTION_ID = XDL.APPLIED_TO_DIST_ID_NUM_1
   ✅ Nouvelle : RT.TRANSACTION_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1
                 PDA.PO_DISTRIBUTION_ID = RT.PO_DISTRIBUTION_ID

4. TYPES DE TRANSACTIONS RCV POSSIBLES :
   - RECEIVE (réception standard)
   - CORRECT (correction de réception)
   - RETURN TO VENDOR (retour fournisseur)
   - RETURN TO RECEIVING (retour à la réception)

5. POURQUOI CERTAINES RCV N'ONT PAS DE PO :
   - Réceptions directes (Direct Delivery)
   - Réceptions sans PO (Expense Destination)
   - Corrections/Ajustements manuels
*/
