select * from (SELECT GJL.JE_HEADER_ID,
       GJL.JE_LINE_NUM,
       RT.TRANSACTION_ID AS RCV_TRANSACTION_ID,
       PDA.PO_DISTRIBUTION_ID,
       POH.SEGMENT1 AS PO_NUMBER,
       GJL.LEDGER_ID,
       RT.ORGANIZATION_ID,
       GJL.CREATION_DATE,
       GJH.PERIOD_NAME
  FROM GL.GL_JE_LINES GJL
 INNER JOIN GL.GL_LEDGERS GLE ON GLE.LEDGER_ID = GJL.LEDGER_ID
 INNER JOIN GL.GL_JE_HEADERS GJH ON GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
 INNER JOIN GL.GL_JE_BATCHES GJB ON GJB.JE_BATCH_ID = GJH.JE_BATCH_ID
 INNER JOIN XLA.XLA_AE_LINES XAL
     ON (XAL.GL_SL_LINK_ID = GJL.GL_SL_LINK_ID
         AND XAL.ACCOUNTING_CLASS_CODE = 'CHARGE'
         AND XAL.GL_SL_LINK_TABLE = 'XLAJEL')
 LEFT OUTER JOIN XLA.XLA_AE_HEADERS XAH
     ON XAH.AE_HEADER_ID = XAL.AE_HEADER_ID
 LEFT OUTER JOIN XLA.XLA_DISTRIBUTION_LINKS XDL
     ON (XDL.AE_HEADER_ID = XAH.AE_HEADER_ID
         AND XDL.AE_LINE_NUM = XAL.AE_LINE_NUM)
 LEFT OUTER JOIN PO.RCV_TRANSACTIONS RT
     ON RT.TRANSACTION_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1
     AND XDL.SOURCE_DISTRIBUTION_TYPE = 'RCV_RECEIVING_SUB_LEDGER'
 LEFT OUTER JOIN PO.PO_DISTRIBUTIONS_ALL PDA
     ON PDA.PO_DISTRIBUTION_ID = RT.PO_DISTRIBUTION_ID
 LEFT OUTER JOIN PO.PO_HEADERS_ALL POH
     ON POH.PO_HEADER_ID = PDA.PO_HEADER_ID
 WHERE GJH.PERIOD_NAME = 'NOV-25'
   AND GLE.LEDGER_CATEGORY_CODE = 'PRIMARY'
   AND GJH.JE_SOURCE = 'Cost Management'
   AND GJH.JE_CATEGORY = 'Accrual'
   AND GJL.GL_SL_LINK_ID IS NOT NULL
   AND RT.TRANSACTION_ID IS NOT NULL
   AND SUBSTR(GJB.NAME, 1, 9) = 'PROVISION'
   AND GJB.DEFAULT_PERIOD_NAME = GJH.PERIOD_NAME
UNION ALL
-- Deuxième partie : GL_SL_LINK_ID NULL (via GL_IMPORT_REFERENCES)
SELECT GJL.JE_HEADER_ID,
       GJL.JE_LINE_NUM,
       RT.TRANSACTION_ID AS RCV_TRANSACTION_ID,
       PDA.PO_DISTRIBUTION_ID,
       POH.SEGMENT1 AS PO_NUMBER,
       GJL.LEDGER_ID,
       RT.ORGANIZATION_ID,
       GJL.CREATION_DATE,
       GJH.PERIOD_NAME
  FROM GL.GL_JE_LINES GJL
 INNER JOIN GL.GL_LEDGERS GLE ON GLE.LEDGER_ID = GJL.LEDGER_ID
 INNER JOIN GL.GL_JE_HEADERS GJH ON GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
 INNER JOIN GL.GL_JE_BATCHES GJB ON GJB.JE_BATCH_ID = GJH.JE_BATCH_ID
 LEFT OUTER JOIN GL.GL_IMPORT_REFERENCES GIR
     ON (GIR.JE_HEADER_ID = GJL.JE_HEADER_ID
         AND GIR.JE_LINE_NUM = GJL.JE_LINE_NUM)
 LEFT OUTER JOIN XLA.XLA_AE_LINES XAL
     ON (XAL.GL_SL_LINK_ID = GIR.GL_SL_LINK_ID
         AND XAL.ACCOUNTING_CLASS_CODE = 'CHARGE'
         AND XAL.GL_SL_LINK_TABLE = 'XLAJEL')
 LEFT OUTER JOIN XLA.XLA_AE_HEADERS XAH
     ON XAH.AE_HEADER_ID = XAL.AE_HEADER_ID
 LEFT OUTER JOIN XLA.XLA_DISTRIBUTION_LINKS XDL
     ON (XDL.AE_HEADER_ID = XAH.AE_HEADER_ID
         AND XDL.AE_LINE_NUM = XAL.AE_LINE_NUM)
 LEFT OUTER JOIN PO.RCV_TRANSACTIONS RT
     ON RT.TRANSACTION_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1
     AND XDL.SOURCE_DISTRIBUTION_TYPE = 'RCV_RECEIVING_SUB_LEDGER'
 LEFT OUTER JOIN PO.PO_DISTRIBUTIONS_ALL PDA
     ON PDA.PO_DISTRIBUTION_ID = RT.PO_DISTRIBUTION_ID
 LEFT OUTER JOIN PO.PO_HEADERS_ALL POH
     ON POH.PO_HEADER_ID = PDA.PO_HEADER_ID
 WHERE GJH.PERIOD_NAME = 'NOV-25'
   AND GLE.LEDGER_CATEGORY_CODE = 'PRIMARY'
   AND GJH.JE_SOURCE = 'Cost Management'
   AND GJH.JE_CATEGORY = 'Accrual'
   AND GJL.GL_SL_LINK_ID IS NULL
   AND RT.TRANSACTION_ID IS NOT NULL
   AND SUBSTR(GJB.NAME, 1, 9) = 'PROVISION'
   AND GJB.DEFAULT_PERIOD_NAME = GJH.PERIOD_NAME
   AND (GJL.ENTERED_DR IS NOT NULL AND GJL.ENTERED_DR <> 0)
ORDER BY 1, 2
)WHERE JE_HEADER_ID =20969911