exec fnd_global.apps_initialize(1323, 50937, 222, 0);
call FND_GLOBAL.APPS_INITIALIZE(user_id => 36313,resp_id => 51214,resp_appl_id => 50001);
--Nouvelle version de la requête de provision compatible OCT-25 et NOV-25
select * from (SELECT GJL.JE_HEADER_ID,
       GJL.JE_LINE_NUM,
       PDA.PO_DISTRIBUTION_ID,
       POH.SEGMENT1 AS PO_NUMBER,
       GJL.LEDGER_ID,
       RT.ORGANIZATION_ID,
       GJL.CREATION_DATE,
       GJH.PERIOD_NAME
  FROM GL.GL_JE_LINES GJL
 INNER JOIN GL.GL_LEDGERS GLE ON GLE.LEDGER_ID = GJL.LEDGER_ID
 INNER JOIN GL.GL_JE_HEADERS GJH ON GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
 INNER JOIN GL.GL_JE_BATCHES GJB ON GJB.JE_BATCH_ID = GJH.JE_BATCH_ID
 INNER JOIN XLA.XLA_AE_LINES XAL
     ON (XAL.GL_SL_LINK_ID = GJL.GL_SL_LINK_ID
         AND XAL.ACCOUNTING_CLASS_CODE = 'CHARGE'
         AND XAL.GL_SL_LINK_TABLE = 'XLAJEL')
 LEFT OUTER JOIN XLA.XLA_AE_HEADERS XAH
     ON XAH.AE_HEADER_ID = XAL.AE_HEADER_ID
 LEFT OUTER JOIN XLA.XLA_DISTRIBUTION_LINKS XDL
     ON (XDL.AE_HEADER_ID = XAH.AE_HEADER_ID
         AND XDL.AE_LINE_NUM = XAL.AE_LINE_NUM)
 LEFT OUTER JOIN PO.RCV_TRANSACTIONS RT
     ON RT.TRANSACTION_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1
     AND XDL.SOURCE_DISTRIBUTION_TYPE = 'RCV_RECEIVING_SUB_LEDGER'
 -- ✅ JOINTURE CORRIGÉE : Utilise COALESCE pour prioriser APPLIED_TO (OCT-25) puis RCV (NOV-25)
 LEFT OUTER JOIN PO.PO_DISTRIBUTIONS_ALL PDA
     ON PDA.PO_DISTRIBUTION_ID = COALESCE(
            XDL.APPLIED_TO_DIST_ID_NUM_1,  -- Priorité 1: Commande de remplacement/correction (OCT-25)
            RT.PO_DISTRIBUTION_ID          -- Priorité 2: Commande originale (NOV-25)
        )
 LEFT OUTER JOIN PO.PO_HEADERS_ALL POH
     ON POH.PO_HEADER_ID = COALESCE(
            PDA.PO_HEADER_ID,              -- Via PO_DISTRIBUTIONS_ALL
            RT.PO_HEADER_ID                -- Direct depuis RCV_TRANSACTIONS
        )
 WHERE GJH.PERIOD_NAME = 'OCT-25'
   AND GLE.LEDGER_CATEGORY_CODE = 'PRIMARY'
   AND GJH.JE_SOURCE = 'Cost Management'
   AND GJH.JE_CATEGORY = 'Accrual'
   AND GJL.GL_SL_LINK_ID IS NOT NULL
   AND RT.TRANSACTION_ID IS NOT NULL
   AND SUBSTR(GJB.NAME, 1, 9) = 'PROVISION'
   AND GJB.DEFAULT_PERIOD_NAME = GJH.PERIOD_NAME
UNION ALL
-- Deuxième partie : GL_SL_LINK_ID NULL (via GL_IMPORT_REFERENCES)
SELECT GJL.JE_HEADER_ID,
       GJL.JE_LINE_NUM,
       PDA.PO_DISTRIBUTION_ID,
       POH.SEGMENT1 AS PO_NUMBER,
       GJL.LEDGER_ID,
       RT.ORGANIZATION_ID,
       GJL.CREATION_DATE,
       GJH.PERIOD_NAME
  FROM GL.GL_JE_LINES GJL
 INNER JOIN GL.GL_LEDGERS GLE ON GLE.LEDGER_ID = GJL.LEDGER_ID
 INNER JOIN GL.GL_JE_HEADERS GJH ON GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
 INNER JOIN GL.GL_JE_BATCHES GJB ON GJB.JE_BATCH_ID = GJH.JE_BATCH_ID
 LEFT OUTER JOIN GL.GL_IMPORT_REFERENCES GIR
     ON (GIR.JE_HEADER_ID = GJL.JE_HEADER_ID
         AND GIR.JE_LINE_NUM = GJL.JE_LINE_NUM)
 LEFT OUTER JOIN XLA.XLA_AE_LINES XAL
     ON (XAL.GL_SL_LINK_ID = GIR.GL_SL_LINK_ID
         AND XAL.ACCOUNTING_CLASS_CODE = 'CHARGE'
         AND XAL.GL_SL_LINK_TABLE = 'XLAJEL')
 LEFT OUTER JOIN XLA.XLA_AE_HEADERS XAH
     ON XAH.AE_HEADER_ID = XAL.AE_HEADER_ID
 LEFT OUTER JOIN XLA.XLA_DISTRIBUTION_LINKS XDL
     ON (XDL.AE_HEADER_ID = XAH.AE_HEADER_ID
         AND XDL.AE_LINE_NUM = XAL.AE_LINE_NUM)
 LEFT OUTER JOIN PO.RCV_TRANSACTIONS RT
     ON RT.TRANSACTION_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1
     AND XDL.SOURCE_DISTRIBUTION_TYPE = 'RCV_RECEIVING_SUB_LEDGER'
 -- ✅ JOINTURE CORRIGÉE : Utilise COALESCE pour prioriser APPLIED_TO (OCT-25) puis RCV (NOV-25)
 LEFT OUTER JOIN PO.PO_DISTRIBUTIONS_ALL PDA
     ON PDA.PO_DISTRIBUTION_ID = COALESCE(
            XDL.APPLIED_TO_DIST_ID_NUM_1,  -- Priorité 1: Commande de remplacement/correction (OCT-25)
            RT.PO_DISTRIBUTION_ID          -- Priorité 2: Commande originale (NOV-25)
        )
 LEFT OUTER JOIN PO.PO_HEADERS_ALL POH
     ON POH.PO_HEADER_ID = COALESCE(
            PDA.PO_HEADER_ID,              -- Via PO_DISTRIBUTIONS_ALL
            RT.PO_HEADER_ID                -- Direct depuis RCV_TRANSACTIONS
        )
 WHERE GJH.PERIOD_NAME = 'OCT-25'
   AND GLE.LEDGER_CATEGORY_CODE = 'PRIMARY'
   AND GJH.JE_SOURCE = 'Cost Management'
   AND GJH.JE_CATEGORY = 'Accrual'
   AND GJL.GL_SL_LINK_ID IS NULL
   AND RT.TRANSACTION_ID IS NOT NULL
   AND SUBSTR(GJB.NAME, 1, 9) = 'PROVISION'
   AND GJB.DEFAULT_PERIOD_NAME = GJH.PERIOD_NAME
   AND (GJL.ENTERED_DR IS NOT NULL AND GJL.ENTERED_DR <> 0)
ORDER BY 1, 2
)WHERE JE_HEADER_ID =20730055 ;


-- Fin de la nouvelle version de la requête de provision compatible OCT-25 et NOV-25

--Ancienne version de la requête de provision OCT-25 uniquement
exec fnd_global.apps_initialize(1323, 50937, 222, 0);
SELECT * FROM (
SELECT GJL.JE_HEADER_ID,
       GJL.JE_LINE_NUM,
       PDA.PO_DISTRIBUTION_ID,
       GJL.LEDGER_ID,
       PDA.ORG_ID,
       GJL.CREATION_DATE,
       GJH.PERIOD_NAME,
       XDL.SOURCE_DISTRIBUTION_ID_NUM_1,
       XDL.SOURCE_DISTRIBUTION_TYPE,
       RT.TRANSACTION_ID
  FROM GL.GL_JE_LINES GJL
     INNER JOIN GL.GL_LEDGERS GLE ON GLE.LEDGER_ID = GJL.LEDGER_ID
     INNER JOIN GL.GL_JE_HEADERS GJH ON GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
     INNER JOIN GL.GL_JE_BATCHES GJB ON GJB.JE_BATCH_ID = GJH.JE_BATCH_ID
     INNER JOIN XLA.XLA_AE_LINES XAL
         ON (    XAL.GL_SL_LINK_ID = GJL.GL_SL_LINK_ID
             AND XAL.ACCOUNTING_CLASS_CODE = 'CHARGE'
             AND XAL.gl_sl_link_table = 'XLAJEL')
     LEFT OUTER JOIN XLA.xla_ae_headers XAH
         ON XAH.ae_header_id = XAL.ae_header_id
     LEFT OUTER JOIN XLA.xla_distribution_links XDL
         ON (    XDL.ae_header_id = XAH.ae_header_id
             AND XDL.ae_line_num = XAL.ae_line_num)
     LEFT OUTER JOIN PO.RCV_TRANSACTIONS RT
         ON RT.TRANSACTION_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1
         AND XDL.SOURCE_DISTRIBUTION_TYPE = 'RCV_RECEIVING_SUB_LEDGER'
     LEFT OUTER JOIN po.po_distributions_all pda
         ON PDA.po_distribution_id = XDL.APPLIED_TO_DIST_ID_NUM_1
 WHERE     gjh.period_name = 'OCT-25'
     AND GLE.LEDGER_CATEGORY_CODE = 'PRIMARY'
     AND gjh.je_source = 'Cost Management'
     AND gjh.je_category = 'Accrual'
     AND GJL.GL_SL_LINK_ID IS NOT NULL
     AND pda.PO_DISTRIBUTION_ID IS NOT NULL
     AND (    SUBSTR (GJB.NAME, 1, 9) = 'PROVISION'
--   AND SUBSTR (GJB.NAME,(INSTR (GJB.NAME,'_',1,2)+ 1),6) --HNB 23/09/2024 KDFI-1702
     AND GJB.default_period_name = gjh.period_name) --HNB 23/09/2024 KDFI-1702
UNION ALL
  -- GJL.GL_SL_LINK_ID is null
SELECT GJL.JE_HEADER_ID,
       GJL.JE_LINE_NUM,
       PDA.PO_DISTRIBUTION_ID,
       GJL.LEDGER_ID,
       PDA.ORG_ID,
       GJL.CREATION_DATE,
       GJH.PERIOD_NAME,
       XDL.SOURCE_DISTRIBUTION_ID_NUM_1,
       XDL.SOURCE_DISTRIBUTION_TYPE,
       RT.TRANSACTION_ID
  FROM gl.gl_je_lines gjl
     INNER JOIN GL.GL_LEDGERS GLE ON GLE.LEDGER_ID = GJL.LEDGER_ID
     INNER JOIN GL.GL_JE_HEADERS GJH ON GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
     INNER JOIN GL.GL_JE_BATCHES GJB ON GJB.JE_BATCH_ID = GJH.JE_BATCH_ID
     LEFT OUTER JOIN gl.gl_import_references gir
         ON (    GIR.JE_HEADER_ID = GJL.JE_HEADER_ID
             AND gir.JE_LINE_NUM = GJL.JE_LINE_NUM)
     LEFT OUTER JOIN XLA.XLA_AE_LINES XAL
         ON (    XAL.GL_SL_LINK_ID = GIR.GL_SL_LINK_ID
             AND XAL.ACCOUNTING_CLASS_CODE = 'CHARGE'
             AND XAL.gl_sl_link_table = 'XLAJEL')
     LEFT OUTER JOIN XLA.xla_ae_headers XAH
         ON XAH.ae_header_id = XAL.ae_header_id
     LEFT OUTER JOIN XLA.xla_distribution_links XDL
         ON (    XDL.ae_header_id = XAH.ae_header_id
             AND XDL.ae_line_num = XAL.ae_line_num)
     LEFT OUTER JOIN PO.RCV_TRANSACTIONS RT
         ON RT.TRANSACTION_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1
         AND XDL.SOURCE_DISTRIBUTION_TYPE = 'RCV_RECEIVING_SUB_LEDGER'
     LEFT OUTER JOIN po.po_distributions_all pda
         ON PDA.po_distribution_id = XDL.APPLIED_TO_DIST_ID_NUM_1
 WHERE  gjh.period_name = 'OCT-25'
     AND GLE.LEDGER_CATEGORY_CODE = 'PRIMARY'
     AND gjh.je_source = 'Cost Management'
     AND gjh.je_category = 'Accrual'
     AND GJL.GL_SL_LINK_ID IS NULL
     AND pda.PO_DISTRIBUTION_ID IS NOT NULL
     AND (    SUBSTR (GJB.NAME, 1, 9) = 'PROVISION'
--   AND SUBSTR (GJB.NAME,(INSTR (GJB.NAME,'_',1,2)+ 1),6)--HNB 23/09/2024 KDFI-1702
     AND GJB.default_period_name = gjh.period_name) --HNB 23/09/2024 KDFI-1702
     AND (gjl.entered_dr IS NOT NULL AND gjl.entered_dr <> 0)
ORDER BY 1, 2
)WHERE 1 = 1
AND JE_HEADER_ID =20730055;