#	---------------------------------------------------------------------
#			CONFIGURATION DES BASES DE DONNEES
#	---------------------------------------------------------------------
[env]
#environnement=run
environnement=dev

[config_oracle_finance]
BASE_URL = prdscanc1pdb03.dalkia.net
BASE_PORT = 1521
BASE_SERVICE_NAME = ebs_PDBFINP1
TYPE = ORACLE
DB_USER = DKA_JMETER_ST
DB_PASSWORD = SupervisionDk

[config_oracle_test]
BASE_URL = etiscandb03.eti.dalkia.net
BASE_PORT = 1521
BASE_SERVICE_NAME = ebs_PDBFINI2
TYPE = ORACLE
DB_USER = DKA_JMETER_ST
DB_PASSWORD = SupervisionDk